### ISSUE TITLE
neural_style.lua using only 1 CPU

### ISSUE THREAD

**Issue by Eibriel** [nagadomi/waifu2x#105]
I'm running neural_style.lua inside a Docker container on a 8 core machine, but the process uses only 1 CPU. Is that normal?

My Docker command:
```
docker pull kchentw/neural-style
docker run -it -m 4g --cpuset-cpus 4 -v /images:/root/work kchentw/neural-style bash
cd /root/neural-style
th neural_style.lua -gpu -1 -style_image /root/work/style.jpg -content_image /root/work/content.jpg -output_image /root/work/mix.png
```

![seleccion_159](https://cloud.githubusercontent.com/assets/172656/14611839/9d2172b8-056a-11e6-8038-1aae188962ef.png)

Thanks!

**Comment by nagadomi** [comment]
Here is not neural-style repo.
