### ISSUE TITLE
error when run waifu2x.lua

### ISSUE THREAD

**Issue by bobbyboga** [nagadomi/waifu2x#109]
root@ubuntu-1gb-nyc2-01:~/waifu2x# th waifu2x.lua
/root/torch/install/bin/lua: /root/torch/install/share/lua/5.2/trepl/init.lua:384: /root/torch/install/share/lua/5.2/trepl/init.lua:384: /root/torch/install/share/lua/5.2/torch/init.lua:102: bad argument #2 (invalid parent class name nn.Module)
stack traceback:
        [C]: in function 'error'
        /root/torch/install/share/lua/5.2/trepl/init.lua:384: in function 'require'
        waifu2x.lua:5: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: in ?

whats thats mean? what should i fix?

**Comment by nagadomi** [comment]
Maybe that is CUDA error.
I added the error message at https://github.com/nagadomi/waifu2x/commit/5bfe504de1d4561a40eda3aa7ecbd2fa5024caf3

Try to install cutorch and cunn.
```
luarocks install cutorch
luarocks install cunn
```
And verify a installation.
```
th -e "require 'cunn'"
```

**Comment by bobbyboga** [comment]
Always error when install them.
luarocks install cutorch show error

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /root/torch/install
CMake Error at /usr/share/cmake-2.8/Modules/FindCUDA.cmake:548 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:7 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cutorch-scm-1-6417/cutorch/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.
root@ubuntu-1gb-nyc2-01:~#
------------------------------------------------------------------------------------------------------------
and when i install cunn
-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cutorch-scm-1-2959/cutorch/build/CMakeFiles/CMakeOutput.log".

Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec - Build error: Failed building.

**Comment by nagadomi** [comment]
It seems that CUDA is not installed correctly.
See http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-linux/index.html or google "cuda install [your platform]"

**Comment by bobbyboga** [comment]
i know my problem. my vga doen't support cuda. 
00:02.0 VGA compatible controller [0300]: Cirrus Logic GD 5446 [1013:00b8] (prog-if 00 [VGA controller])
can i installed on non nvidia? btw i want install on my vps

**Comment by nagadomi** [comment]
My implementation requires CUDA.
[waifu2x-caffe](https://github.com/lltcggie/waifu2x-caffe)([my linux build](https://github.com/nagadomi/waifu2x-caffe)) and [waifu2x-converter-cpp](https://github.com/tanakamura/waifu2x-converter-cpp) supports CPU mode.
