### ISSUE TITLE
be online

### ISSUE THREAD

**Issue by ryuu9** [nagadomi/waifu2x#113]
i want install it an make it online. but, as i know vps does't support for installing cuda. how u make in online? (like demo)

**Comment by nagadomi** [comment]
`waifu2x.udp.jp` is hosted on AWS EC2 GPU Instance (g2.2xlarge or g2.8xlarge).

**Comment by ryuu9** [comment]
so. its not vps like DO. thats so expensive for me. :smile:

**Comment by ryuu9** [comment]
can waifu2x run on ordinary vps?

**Comment by nagadomi** [comment]
No. My implementation requires CUDA and GPU. But other implementation (e.g. waifu2x-converter-cpp) can run on ordinary vps with CPU mode.

**Comment by ryuu9** [comment]
okay. arigatou :laughing:
