### ISSUE TITLE
The [Video Encoding] section in README is a bit wrong

### ISSUE THREAD

**Issue by GhettoGirl** [nagadomi/waifu2x#119]
Hi nagadomi,

I want to report a problem with one command in the __Video Encoding__ section in the ```README.md```

---

You specified the following command to convert the frames back to a video:

```avconv -f image2 -r 24 -i new_frames/%d.png -i audio.mp3 -r 24 -vcodec libx264 -crf 16 video.mp4```

This is wrong because the ```image2``` format doesn't take the ```-r``` option to force the framerate. According to the ffmpeg docs it must be ```-framerate```.
So the new command whould look like this:
```avconv -f image2 -framerate 24 -i new_frames/%d.png -i audio.mp3 -r 24 -vcodec libx264 -crf 16 video.mp4```

---

ffmpeg ignores the ```-r``` option for ```image2``` completely, which causes a __audio-video-desync__ (the video is faster than the audio). Depending on the actual video length it drops about ~5 frames per second, because ffmpeg defaults to 25 frames for the ```image2``` format.

If someone for example generates images with a framerate like 30, rather than 24, and than converts back the frames to the video, the audio and video tracks are out of sync.

You should fix this in the readme :)

Regards

**Comment by nagadomi** [comment]
I fixed that. Thanks. 

> You can specify two frame rates:
> 
> The rate according to which the images are read, by setting -framerate before -i. The default for reading input is -framerate 25 which will be set if no -framerate is specified.
> The output frame rate for the video stream by setting -r after -i or by using the fps filter. If you want the input and output frame rates to be the same, then just declare an input -framerate and the output will inherit the same value.
> 
https://trac.ffmpeg.org/wiki/Create%20a%20video%20slideshow%20from%20images
