### ISSUE TITLE
Run this without CUDA?

### ISSUE THREAD

**Issue by chengyuhui** [nagadomi/waifu2x#12]
Is it possible to run this application on system without NVIDIA graphic card?

**Comment by nagadomi** [comment]
No.

**Comment by an-electric-sheep** [comment]
It may be possible to run this on a CPU by changing all instances of `CudaTensor` to `FloatTensor`, replacing `cudnn` module with `nn` and replacing various `:cuda()` method calls in the source.

With [additional substitutions](https://github.com/jonathantompson/jtorch) OpenCL *might* work for applying the model but not for training it.

But this will be __*extremely*__ slow.

**Comment by nagadomi** [comment]
You are right. In officially, waifu2x supports only cuDNN. but,
You can run on CPU If replace `cudnn.SpatialConvolution` with `nn.SpatialConvolutionMM` in `lib/srcnn.lua` and use https://github.com/soumith/fakecuda .

**Comment by nagadomi** [comment]
and this code is cool.
```
waifu2x upscaling, done in 35 lines of Python: https://mrcn.st/t/waifu2x.py  
https://mrcn.st/t/scale2.0x_model.json … PyOpenCL version next? 
```
from https://twitter.com/marcan42/status/601456859556417536

**Comment by darkdragon-001** [comment]
> from https://twitter.com/marcan42/status/601456859556417536

OpenCL implementation from the same guy: https://github.com/marcan/cl-waifu2x
