### ISSUE TITLE
Website Upload Limits Incorrect

### ISSUE THREAD

**Issue by Metaception** [nagadomi/waifu2x#129]
The stated upload limits: _5MB, Noise Reduction: 3000x3000px, Upscaling: 1500x1500px._
Is either incorrectly implemented or mislabeled.

Tested used a 1501x1500 blank PNG with Upscaling set to **None**.
Since this is only Noise Reduction, the limit should be 3000x3000 (Image size is 3KB).
This returns: _ERROR: image size exceeds maximum allowable size._

The website appears to be using the Upscaling limits for all images.

**Comment by nagadomi** [comment]
You are right. That is bug. Now I fixed this bug and updated http://waifu2x.udp.jp/.
Thank you for reporting this issue.
