### ISSUE TITLE
Magick: abort due to signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by VBChunguk** [nagadomi/waifu2x#131]
After I updated from outdated `upconv` branch to `master`, I got this error message:

```
Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
```

and nothing.

I `git bisect`ed, and found out that 3b72864 is the first commit that the problem happens. I have no idea what's going on; I've updated Torch7 and rocks, but it still happens. Maybe the updated model is the problem? But why `Magick`? I don't know...

I'm using up-to-date Arch Linux 64bit. No `-force_cudnn` used.

**Comment by nagadomi** [comment]
waifu2x is using GraphicsMagick. Maybe it is related.
Did you update  graphicsmagick package?
```
luarocks install graphicsmagick
```
But I am not sure why is https://github.com/nagadomi/waifu2x/commit/3b728643ec382242815dc3f60cc1f3e772aee688.
Did you update nn&cunn with luarocks command?
```
luarocks install nn
luarocks install cunn
```

If this issue cannot be solved, could you check the backtrace?
```
$ gdb luajit
> run waifu2x.lua
> bt
```

**Comment by VBChunguk** [comment]
I have updated nn and graphicsmagick(and that Magick error occurs), but updating cunn failed with lots of compile errors. I'll find out what's wrong and update cunn as soon as possible. I don't have much time nowadays :(

**Comment by VBChunguk** [comment]
It seems that Arch Linux is not compatible with recent CUDA luarocks. I'll close this issue for now.

**Comment by VBChunguk** [comment]
Finally succeeded to update cunn(it was kinda easy), and it works well. Thanks!

**Comment by benounnas** [comment]
if you face this in laravel xD, i know it's silly but i forgot the env :/ 
(may be someone like me who sees the same)
