### ISSUE TITLE
Fail to Run th waifu2x.lua | waifu2x.lua:42: attempt to index local 'meta' (a nil value)

### ISSUE THREAD

**Issue by lordwarlock** [nagadomi/waifu2x#133]
Hi, I installed Torch7 and related packages using luarocks, when I run "th waifu2x.lua", I met this error 
/torch/install/bin/lua: waifu2x.lua:42: attempt to index local 'meta' (a nil value)
stack traceback:
	waifu2x.lua:42: in function 'convert_image'
	waifu2x.lua:283: in function 'waifu2x'
	waifu2x.lua:288: in main chunk
	[C]: in function 'dofile'
	.../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: ?

Do you know how to solve it?

**Comment by nagadomi** [comment]
That is image loading error. I've added error message.
But I am not sure why failed to load PNG image.
Does your system have libpng?
Try
```
sudo apt-get install libpng-dev
```

**Comment by lordwarlock** [comment]
I have libpng-1.5.13-7.el7_2.x86_64, libpng-devel-1.5.13-7.el7_2.x86_64 and GraphicsMagick-devel-1.3.24-1.el7.x86_64
My OS is RHEL 7.2

**Comment by lordwarlock** [comment]
It seems that im:colorspace() in line 76 of image_loader has some problems,
th> im:colorspace()
unable to convert argument 1 from cdata<double> to cdata<intptr_t>
stack traceback:
	.../zhihaozh/torch/install/share/lua/5.1/trepl/init.lua:501: in function <.../zhihaozh/torch/install/share/lua/5.1/trepl/init.lua:494>
	[C]: in function 'tonumber'
	...torch/install/share/lua/5.1/graphicsmagick/Image.lua:620: in function 'colorspace'
	[string "_RESULT={im:colorspace()}"]:1: in main chunk
	[C]: in function 'xpcall'
	.../zhihaozh/torch/install/share/lua/5.1/trepl/init.lua:652: in function 'repl'
	.../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: ?	

I've no idea about torch, do you have any idea about what may cause this?

**Comment by nagadomi** [comment]
Maybe it is a problem of lua interpreter or FFI. ?

http://luajit.org/ext_ffi_api.html describes this.
>Extended Standard Library Functions
>The following standard library functions have been extended to work with cdata objects:
>n = tonumber(cdata)

But your system seems does not support `tonumber(cdata)`.
Are you using LuaJIT?

Here is a version of th/luajit on my env.
```
% cat `which th`
#!/bin/sh

exec '/home/nagadomi/torch/install/bin/luajit' -e 'package.path="/home/nagadomi/.luarocks/share/lua/5.1/?.lua;/home/nagadomi/.luarocks/share/lua/5.1/?/init.lua;/home/nagadomi/torch/install/share/lua/5.1/?.lua;/home/nagadomi/torch/install/share/lua/5.1/?/init.lua;"..package.path; package.cpath="/home/nagadomi/.luarocks/lib/lua/5.1/?.so;/home/nagadomi/torch/install/lib/lua/5.1/?.so;"..package.cpath' -e 'local k,l,_=pcall(require,"luarocks.loader") _=k and l.add_context("trepl","scm-1")' '/home/nagadomi/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th' "$@"

% /home/nagadomi/torch/install/bin/luajit -v
LuaJIT 2.1.0-beta1 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
 _____              _     
|_   _|            | |    
  | | ___  _ __ ___| |__  
  | |/ _ \| '__/ __| '_ \ 
  | | (_) | | | (__| | | |
  \_/\___/|_|  \___|_| |_|
```

**Comment by lordwarlock** [comment]
Solved. I was using lua5.1. Now I'm using luajit and it works. Thanks!
