### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by mingchen62** [nagadomi/waifu2x#134]
Hats off to nagadomi for a good job. I am able to get it running to get good results.
but I encounter some memory issues. 
Each time I ran it,I noticed the memory used increased and never get released. Over the time, the system become unusable. and I have to reboot. I can reproduce this memory "leak?" issue  using a loop:

 COUNTER=200
         until [  $COUNTER -lt 1 ]; do
             echo COUNTER $COUNTER
                sleep 3
                th ~/waifu2x/waifu2x.lua  -model_dir models/photo -m noise_scale -noise_level 1 -i images/city.jpg -o test.jpg
             let COUNTER-=1
         done

/usr/local/cuda/samples/1_Utilities/deviceQuery$ ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX 980 Ti"
  CUDA Driver Version / Runtime Version          7.5 / 7.5
  CUDA Capability Major/Minor version number:    5.2
  Total amount of global memory:                 6144 MBytes (6442254336 bytes)
  (22) Multiprocessors, (128) CUDA Cores/MP:     2816 CUDA Cores
  GPU Max Clock rate:                            1076 MHz (1.08 GHz)
  Memory Clock rate:                             3505 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 3145728 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536),                                                                                                                      3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simu                                                                                                                     ltaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 7.5, CUDA Runtime Versi                                                                                                                     on = 7.5, NumDevs = 1, Device0 = GeForce GTX 980 Ti
Result = PASS

I am on ubuntu 14.04 LTS, 64 and Torch 7.

**Comment by mingchen62** [comment]
to add: 
GPU memory seems fine:
 nvidia-smi
Tue Aug  2 08:45:13 2016
+------------------------------------------------------+
| NVIDIA-SMI 352.93     Driver Version: 352.93         |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980 Ti  Off  | 0000:01:00.0     Off |                  N/A |
| 22%   56C    P2    91W / 250W |    404MiB /  6143MiB |     47%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      8789    C   /home/hope/torch/install/bin/luajit            382MiB |
+-----------------------------------------------------------------------------+

potential memory leak in system:

top - 08:46:44 up 29 min,  4 users,  load average: 0.75, 0.60, 0.37
Tasks: 175 total,   2 running, 173 sleeping,   0 stopped,   0 zombie
%Cpu(s):  6.6 us,  1.7 sy,  0.0 ni, 91.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  16367432 total, 12059620 used,  4307812 free,    20356 buffers
KiB Swap: 16711676 total,        0 used, 16711676 free.   260748 cached Mem

**Comment by nagadomi** [comment]
I can have a look at this issue. but I am guessing that is problem of GPU driver or GPU overheating.
And, it is not a memory leak, I think. Maybe you can free the system memory with
```
sudo /sbin/sysctl -w vm.drop_caches=3
```

**Comment by mingchen62** [comment]
May be a GPU driver issue.
Found a similiar issue at Torch
https://github.com/torch/cutorch/issues/379
Upgrading OS and GPU driver and will update what I find.

**Comment by mingchen62** [comment]
Updated to cuda 8.0 and Nvidia driver verion 367.35 . No more memory issues. closed the issue
