### ISSUE TITLE
Segfault on Nvidia 370.23 drivers

### ISSUE THREAD

**Issue by vonniewu** [nagadomi/waifu2x#139]
**So the problem is the latest Nvidia drivers on Linux (Arch Linux, Kernal 4.7.2-1
Nvidia drivers 370.23) and the latest Cuda toolkit causes the program to segfault on startup.**

Here's the full error report:

Process 3281 (waifu2x) of user 1000 dumped core.

Stack trace of thread 3281:
#0  0x00007f2ec2acdad0 pthread_mutex_lock (libpthread.so.0)
#1  0x00007f2ebd0320e8 n/a (libcuda.so.1)
#2  0x00007f2ebd0e7f91 n/a (libcuda.so.1)
#3  0x00007f2ebd0e8105 n/a (libcuda.so.1)
#4  0x00007f2ebd037e24 n/a (libcuda.so.1)
#5  0x00007f2ebd039677 n/a (libcuda.so.1)
#6  0x00007f2ebd00d846 n/a (libcuda.so.1)
#7  0x00007f2ebd05979d cuInit (libcuda.so.1)
#8  0x00007f2ec62f3a3e _ZN4w2xc14initCUDAGlobalEPSt6vectorI16W2XConvProcessorSaIS1_EE (libw2xc.so)
#9  0x00007f2ec62ffd04 n/a (libw2xc.so)
#10 0x00007f2ec2ad26f9 __pthread_once_slow (libpthread.so.0)
#11 0x00007f2ec62f5407 w2xconv_get_processor_list (libw2xc.so)
#12 0x0000000000408ea1 main (waifu2x)
#13 0x00007f2ec59b0291 __libc_start_main (libc.so.6)
#14 0x000000000040a29a _start (waifu2x)

Stack trace of thread 3293:
#0  0x00007f2ec5a79cd8 accept4 (libc.so.6)
#1  0x00007f2ebe4766a6 n/a (libnvidia-opencl.so.1)
#2  0x00007f2ebe46a4ad n/a (libnvidia-opencl.so.1)
#3  0x00007f2ebe477098 n/a (libnvidia-opencl.so.1)
#4  0x00007f2ec2acb454 start_thread (libpthread.so.0)
#5  0x00007f2ec5a787df __clone (libc.so.6)

**Comment by nagadomi** [comment]
This repository is not for w2xc.
It's over there : https://github.com/tanakamura/waifu2x-converter-cpp
