### ISSUE TITLE
What kind of graphics card and computer would you need?

### ISSUE THREAD

**Issue by PhilAndrew** [nagadomi/waifu2x#14]
So I am thinking to buy a graphics card for this, as I gather it must be a NVida which supports compute capability 3, but even with that requirement there's so many choices of graphics card. Do I need a top-end one? Can you tell me what one you use? How fast or slow is this program with your graphics card?

I don't want to spend a lot of money if I don't need to, but on the other hand if I spend more money what do I get, so I hope you can give some advice as to where the sweet spot is. Also how much RAM on the computer do you suggest?

**Comment by nagadomi** [comment]
I am using GTX760.
Performance: (source image 640x480)
```
2x(->1280x960) + noise reduction: 0.33 fps (3 sec per frame)
2x(->1280x960): 0.44 fps (2.4 sec per frame)
noise reduction: 1.42 fps (0.7 sec per frame)
```
You don't need mush RAM if you don't need to training your own model.
GPU(number of CUDA cores) will affect performance.
