### ISSUE TITLE
Feature suggestion:add image url via request inside site adress

### ISSUE THREAD

**Issue by MasterPetrik** [nagadomi/waifu2x#141]
Services like imdb or google image search are able to make a request to them based on the links of this kind:
http://iqdb.org/?url=
http://www.google.com/searchbyimage?image_url=
http://tineye.com/search/?url=
It is very convenient in many cases, for example when you use Image Search Options(or other analog) plugin in browser.

So it would be very nice to allow such requests using url.
something like this: http://waifu2x.udp.jp/index.html/?url=
Of course, I do not propose to start converting automatically via such links, will be enough to
automatically fill image url field with the address specified in the image url. 
I think this will add the convenience of working with this website. Thanks.

**Comment by YukiSakuma** [comment]
I think your suggestion is similar to this one
https://chrome.google.com/webstore/detail/assist-waifu2x/aopdgjkfalnfokhbgkemiajgfpefgjei

**Comment by nagadomi** [comment]
I've added this feature. The behavior of the querystring parameters are similar to the cookie values(last time settings). But querystring has higher priority than cookie.

example:
http://waifu2x.udp.jp/index.ru.html?url=http://www.scale2x.it/snap/mslugx-1s.png
http://waifu2x.udp.jp/?url=https://upload.wikimedia.org/wikipedia/commons/9/96/2010年今年の漢字.jpg&style=art&noise=3&scale=2
