### ISSUE TITLE
macos 10.12 without Nvida  

### ISSUE THREAD

**Issue by Jamesleons** [nagadomi/waifu2x#144]
i use mac without Nvida device,   can i  use waifu2x to make high image from low image ?

**Comment by GhettoGirl** [comment]
You need a NVIDIA GPU and CUDA to use waifu2x. If you can't satisfy this requirements than you need to use a CPU version of waifu2x which is slower (way slower, I think about 10x times, I don't know).

This version should work: https://github.com/tanakamura/waifu2x-converter-cpp </br> Note that you need [OpenCV](http://opencv.org/) and the [model files](https://github.com/nagadomi/waifu2x/tree/master/models) from waifu2x to use it.

**Comment by nagadomi** [comment]
In this repo, I won't support CPU mode because that is significantly slow.
