### ISSUE TITLE
Suggestion - GUI  

### ISSUE THREAD

**Issue by Zetchzie** [nagadomi/waifu2x#148]
I just love this i was able to beautifully upscale a small image with great results. would a UI be possible? command line is a bit of a hassle

**Comment by nagadomi** [comment]
Use `web.lua` for web interface(it's same as http://waifu2x.udp.jp) or [waifu2x-caffe](https://github.com/lltcggie/waifu2x-caffe)(for windows).

**Comment by Droyk** [comment]
Will you able to tell me which is more updated I think it's the website because whenever I upscale my images with the website the quality seems good & the size seems good too but whenever I try caffe it seems more sharp to eye and become much larger than the website.

**Comment by Zetchzie** [comment]
thanks hope it works as good as the page 😊

**Comment by nagadomi** [comment]
@Droyk 
Do you use the latest version of waifu2x-caffe?
I think that waifu2x-caffe's `2-D illust (UpRGB Model)` is completely the same as our model that is used in our web site.
But, in `Denoise & magnify` mode on UpRGB,  it seems that waifu2x-caffe has a different method than our method. Probably it causes the different results.

**Comment by Droyk** [comment]
Yup I have the latest version it's really sharp and after upscaling size becomes too big even if i compare it to the website one & by the way why don't you make your own application? 
& why on the website you didn't add more upscaling options?

**Comment by nagadomi** [comment]
#118 is related.

**Comment by Droyk** [comment]
if you contributed to the waifu2x-caffe do you know what all the settings means exactly because I use my guess to use the settings will you be able to tell me what those settings means exactly?

and is there is any program that is as good as  waifu2x-caffe and is in active development like your waifu2x project?

**Comment by nagadomi** [comment]
As far as I know, waifu2x-caffe is the only software option that is full compatible with waifu2x(this repo).

**Comment by Droyk** [comment]
> if you contributed to the waifu2x-caffe do you know what all the settings means exactly because I use my guess to use the settings will you be able to tell me what those settings means exactly?

**Comment by nagadomi** [comment]
I've read almost of waifu2x-caffe code and I used it for some closed products.
What is your question? I don't know what you're saying.

**Comment by nagadomi** [comment]
Sorry, I forgot that waifu2x-caffe does not have english documents.
I don't have time for translating documents.

**Comment by Droyk** [comment]
okay will you able to tell me what (Uses of TTA mode) actually means & what split size means?

and I have been seeing on the internet that some people even upscaled videos using waifu2x is that possible if so then how should I do it!

**Comment by nagadomi** [comment]
>TTA

TTA(test-time augmentation) mode averages the upscaling results of the following 8 augmented inputs.
![tta](https://cloud.githubusercontent.com/assets/287255/16225442/86dab704-37e1-11e6-9bbc-093819cd3f6f.png)
TTA mode able to reduce several type of artifacts but it's 8x slower than non TTA mode.

>split size

block size(px) for block processing. larger size might be faster but it increases memory usage. When split size is too large for your GPU memory, runtime error(out of memory) might occur.

>video

1. convert video(all frames) to PNG images (with ffmepg)
2. waifu2x
3. convert waifu2xed images to video (with ffmpeg)

See https://github.com/nagadomi/waifu2x#video-encoding

**Comment by Droyk** [comment]
>convert video(all frames) to PNG images (with ffmepg)
waifu2x
convert waifu2xed images to video (with ffmpeg)

Well that's totally looks a little time consuming work will you able to tell me how much time it will take on a 24 minute episode on i5 gtx970

**Comment by nagadomi** [comment]
You can guess the processing time with waifu2x-caffe. (It will display the processing time)
When, video time=24min, video fps=24, waifu2x processing time for 1 frame = 1sec, 
```
number of images = 1440sec(24min) * 24FPS = 34560 frames
processing time = 34560 * 1(waifu2x sec) = 9.6 hours
```
When the waifu2x processing time for 1 frame = 2sec, it takes around 20 hours.

**Comment by nagadomi** [comment]
another option, VapourSynth supports waifu2x-caffe. https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe
I am not familiar with this software.

**Comment by Droyk** [comment]
Thankyou nagadomi for the help the last question is how do I use VapourSynth I downloaded the files but there is no exe do I have to merge it with caffe then it will work.

**Comment by nagadomi** [comment]
installation: http://www.animemusicvideos.org/forum/viewtopic.php?t=125039#p1546405
waifu2x-caffe plugin binary: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe/releases

 I haven't used this software. It looks a script based tool. Maybe it's hard to use as non programmer users.
