### ISSUE TITLE
Missing AMI

### ISSUE THREAD

**Issue by smuser90** [nagadomi/waifu2x#149]
Hi Nagadomi, 

Great job with waifu! I'm interested in spinning up my own AWS instance but couldn't locate the AMI stated in the readme, or any AMI related to "waifu" keyword using the ec2 search. Has the image been taken down?

Best, 
Sam

**Comment by nagadomi** [comment]
waifu2x-server AMI is only available at `us-east-1 (N.Virginia)` region.
1. Region -> "us-east 1"
2. seach "AMI ID : ami-b9be23ae"

**Comment by smuser90** [comment]
Thanks - found it!
