### ISSUE TITLE
What's the difference between art model and photo model?

### ISSUE THREAD

**Issue by kaca0083** [nagadomi/waifu2x#151]
What's the difference between art model and photo model?
Are they trained with dfferent data with the same network architecture?
Or are they trained with different network architecture?

**Comment by Droyk** [comment]
I want to know this too I have compared some images but they all look the same except the size

**Comment by nagadomi** [comment]
>Are they trained with dfferent data with the same network architecture?
Yes. art model is trained with fanart dataset. photo model is trained with photo dataset. So photo model is specialized for photo.

**Comment by kaca0083** [comment]
@nagadomi 
Thanks for quick reply. Is the fanart dataset available somewhere?

**Comment by nagadomi** [comment]
@kaca0083 
Sorry, my fanart dataset is private. I won't provide it. 
I am working fanart image processing since 2007. The fanart dataset is made by crawling images from 4chan /c/ and danbooru at 2008.

**Comment by kaca0083** [comment]
@nagadomi 
That's all right. Thank you for the information.
