### ISSUE TITLE
[Question] Does the selected mode make a difference for just denoising?

### ISSUE THREAD

**Issue by 0fbcb238c0** [nagadomi/waifu2x#156]
Title

**Comment by nagadomi** [comment]
What does `mode` refer to? waifu2x does not have `-mode` option.

**Comment by 0fbcb238c0** [comment]
I'm sorry I originally wanted to ask this question to the creator of waifu2x-caffe but i can't speak japanese so i thought that maybe waifu2x natively supports modes as in caffe, namely RGB, upRGB, Photo or Y.

**Comment by nagadomi** [comment]
I see, it's `model` option. `model` option makes difference in all conversion results, it also includes `Magnify only`.

**Comment by 0fbcb238c0** [comment]
Thank you
