### ISSUE TITLE
Don't ignore color profile

### ISSUE THREAD

**Issue by trlkly** [nagadomi/waifu2x#158]
It seems that w(a)ifu2x ignores color profiles. Using the website, I put in an image using Adobe RGB, and the colors I got back were very muted. When I converted the original image to sRGB before using waifu, the colors were correct.

If waifu uses 16-bit color internally, the solution is obvious. Read the color profile and use it to map it correctly to the internal profile. Then, before output, map it back to the same profile that was originally used.

If waifu uses 8-bit sRGB internally, then there are two solutions, both with advantages and drawbacks. In this case, it might be good to give the user two options: 

1. Keep the color profile. (Ignore the color profile at first, but then  attach the same profile to the output image.)
2. Convert to the sRGB color profile. 

The first option is easy, and makes sure that no color information is lost. The problem is that the waifu engine would be working with false colors. The second option allows waifu to have the right colors, but can result in color information loss.

**Comment by nagadomi** [comment]
I heard this problem from many users. I will add support for ICC profile.
