### ISSUE TITLE
Application of use on model textures

### ISSUE THREAD

**Issue by leilei-** [nagadomi/waifu2x#16]
Since the issue tracker is apparently the official forum...

While it's too prohibiitively expensive to use at load-time in a videogame, I do find it highly useful seeing what it can do with a compressed 512x512 JPEG texture for an anime-styled character (for say a heavily compacted ~30MB release).

![Sorceress Face](http://leileilol.mancubus.net/crap/sorcwaifu.png)

[Model screenshot of JPEG texture](http://leileilol.mancubus.net/models/sorcwaif3.png)
[Same model, but with Waifu2x'd texture](http://leileilol.mancubus.net/models/sorcwaif4.png)

Can't really use it as is, I use AMD @_@ and it would need a plain C port with OpenCL for it to be hooked into Upload32 in [tr_image.c](https://github.com/OpenArena/engine/blob/master/code/renderer_oa/tr_image.c) for it to really work.  It would be too cumbersome to throw every JPEG texture in through the web demo

Waifu2x is an amazing edgy filterscaler, thanks!  Ends my habit of GIMP Smart Upscale+(Dilate+Octave+Darkness layer) for sure.

**Comment by the8472** [comment]
> Ends my habit of GIMP Smart Upscale+(Dilate+Octave+Darkness layer) for sure.

You might want to look into using warpsharp or [nnedi+superres upscaling filters](http://forum.doom9.org/showthread.php?t=170727) via avisynth or similar rendering pipelines.

They're not as sophisticated as waifu2x but have higher performance.
