### ISSUE TITLE
Failed to load CUDA modules. Please check the CUDA Settings when  I update cuda 

### ISSUE THREAD

**Issue by anthonyyuan** [nagadomi/waifu2x#163]
/Users/anthonyyuan/torch/install/bin/luajit: ...s/anthonyyuan/torch/install/share/lua/5.1/trepl/init.lua:389: lib/w2nn.lua:18: Failed to load CUDA modules. Please check the CUDA Settings.
---
...s/anthonyyuan/torch/install/share/lua/5.1/trepl/init.lua:389: attempt to index a string value
stack traceback:
	[C]: in function 'error'
	...s/anthonyyuan/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	waifu2x.lua:5: in main chunk
	[C]: in function 'dofile'
	...yuan/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x010d4a6bc0

**Comment by nagadomi** [comment]
When you update CUDA, you also have to recompile CUDA kernels of Torch.
```
cd ~/torch
./update.sh
```

**Comment by anthonyyuan** [comment]
Thank u !  Now it works when I run Nivina Cuda Sample !
