### ISSUE TITLE
Error in training

### ISSUE THREAD

**Issue by Lakshya-Kejriwal** [nagadomi/waifu2x#164]
I have a dataset of around 8000 images. I am able to successfully run convert_data.lua, but as soon as I start training I get the following error after validation sets are made:

/usr/local/torch/install/bin/luajit: $ Torch: not enough memory: you tried to allocate 2GB. Buy new RAM! at /tmp/luarocks_torch-scm-1-9354/torch7/lib/TH/THGeneral.c:266
stack traceback:
	[C]: at 0x7fa585ca5ec0
	[C]: in function 'Tensor'
	train.lua:337: in function 'train'
	train.lua:460: in main chunk
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

What is the reason for this error?

**Comment by magiruuvelvet** [comment]
The error message is pretty obious here. How much RAM do you have? Are you using a 32-bit machine? 32-bit can't allocate more than 2~4GB (depends) per process.

**Comment by Lakshya-Kejriwal** [comment]
It's a 64-bit machine and already has 16 GB RAM.

**Comment by magiruuvelvet** [comment]
Really weird then :confused:

**Comment by nagadomi** [comment]
It's a out of memory error. You need to reduce training images or buy RAM.
