### ISSUE TITLE
/home/anthony/torch/install/bin/luajit: cannot open <models/photo/scale2.0x_model.t7> in mode r  at /home/anthony/torch/pkg/torch/lib/TH/THDiskFile.c:678 stack traceback: 	[C]: at 0x7f81f0809cc0 	[C]: in function 'DiskFile' 	/home/anthony/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'

### ISSUE THREAD

**Issue by anthonyyuan** [nagadomi/waifu2x#165]
anthony@anthony-CP77S:~/ccc/tool/waifu2x$ th waifu2x.lua -model_dir models/photo -m scale -i  idcard1.jpg -o idd.png
/home/anthony/torch/install/bin/luajit: cannot open <models/photo/scale2.0x_model.t7> in mode r  at /home/anthony/torch/pkg/torch/lib/TH/THDiskFile.c:678
stack traceback:
	[C]: at 0x7f81f0809cc0
	[C]: in function 'DiskFile'
	/home/anthony/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
	lib/w2nn.lua:23: in function 'load_model'
	waifu2x.lua:77: in function 'convert_image'
	waifu2x.lua:291: in function 'waifu2x'
	waifu2x.lua:296: in main chunk
	[C]: in function 'dofile'
	...hony/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

**Comment by nagadomi** [comment]
I updated torch and tested it. That error did not occur.
See https://github.com/nagadomi/waifu2x/issues/55

**Comment by anthonyyuan** [comment]
thank u ! It is ok!
