### ISSUE TITLE
Recent Papers on Image Super-Resolution

### ISSUE THREAD

**Issue by azurespace** [nagadomi/waifu2x#167]
The authors of SRCNN have published another paper about accelerating SRCNN(FSRCNN).
[Chao Dong, Chen Change Loy, Xiaoou Tang, "Accelerating the Super-Resolution Convolutional Neural Network"](http://mmlab.ie.cuhk.edu.hk/projects/FSRCNN.html)

Deep learning is now applied to reduce mobile network traffic in Google+. This is their paper(RAISR).
[Yaniv Romano, John Isidoro, Peyman Milanfar, "RAISR: Rapid and Accurate Image Super Resolution"](https://arxiv.org/abs/1606.01299)

RAISR can be performed even on a usual smartphone.

**Comment by ProGamerGov** [comment]
What other supper-resolution projects exist at the moment, other than various implementations of Waifu2x?

**Comment by ABDOELSHEMY** [comment]
wow , that great news , would be great if nagadomi have some time to looking in it .

**Comment by azurespace** [comment]
There are some implementations for super-resolution in Github, although this is not a completed service as waifu2x is.

like:
https://github.com/zsdonghao/SRGAN
https://github.com/Hi-king/superresolution_gan
https://github.com/shreka116/SRResNet
