### ISSUE TITLE
error: read 0 blocks instead of 1

### ISSUE THREAD

**Issue by yshua5631** [nagadomi/waifu2x#169]
Hello all,
I ran into this issue:
when i run th waifu2x.lua, the result is images/miku_small_noise_scale.png: 0.69366192817688 sec.
when i run  th waifu2x.lua -m noise -noise_level 1 -i 1.jpg -o output_image.png, there is an error:

/home/yang/torch/install/bin/luajit: /home/yang/torch/install/share/lua/5.1/torch/File.lua:259: read error: read 0 blocks instead of 1 at /tmp/luarocks_torch-scm-1-7753/torch7/lib/TH/THDiskFile.c:349
stack traceback:
	[C]: in function 'readInt'
	/home/yang/torch/install/share/lua/5.1/torch/File.lua:259: in function 'readObject'
	/home/yang/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	lib/w2nn.lua:23: in function 'load_model'
	waifu2x.lua:65: in function 'convert_image'
	waifu2x.lua:291: in function 'waifu2x'
	waifu2x.lua:296: in main chunk
	[C]: in function 'dofile'
	...yang/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

My environment: ubuntu16, cuda8

Can anyone or expert help?

Thanks a lot!

**Comment by nagadomi** [comment]
I am guessing that is torch side issue or model file is broken.
Could you update torch first?
```
cd ~/torch
git pull
./update.sh
```
If issue is not solved, check the model file.
```
% ls -la models/vgg_7/art/noise1_model.t7   
-rw-rw-r-- 1 nagadomi nagadomi 5208717 Jul 21  2016 models/vgg_7/art/noise1_model.t7
% md5sum models/vgg_7/art/noise1_model.t7
fb756ca97d699cbc37d11246f22b3bb0  models/vgg_7/art/noise1_model.t7
% th waifu2x.lua -model_dir models/vgg_7/art -m noise -noise_level 1 -i 1.jpg -o output_image.png
output_image.png: 0.1754138469696 sec	
% th waifu2x.lua -m noise -noise_level 1 -i 1.jpg -o output_image.png 
output_image.png: 0.18308901786804 sec
```

**Comment by yshua5631** [comment]
Interesting. Thanks nagadomi @nagadomi . i follow the steps you mentioned.
when i run  th waifu2x.lua -model_dir models/vgg_7/art -m noise -noise_level 1 -i 1.jpg -o output_image.png, the result is  output_image.png: 0.66157102584839 sec.

when i run  th waifu2x.lua -m noise -noise_level 1 -i 1.jpg -o output_image.png , the previous error stay the same: /home/yang/torch/install/bin/luajit: /home/yang/torch/install/share/lua/5.1/torch/File.lua:259: read error: read 0 blocks instead of 1 at /home/yang/torch/pkg/torch/lib/TH/THDiskFile.c:349
stack traceback:
	[C]: in function 'readInt'
	/home/yang/torch/install/share/lua/5.1/torch/File.lua:259: in function 'readObject'
	/home/yang/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	lib/w2nn.lua:23: in function 'load_model'
	waifu2x.lua:65: in function 'convert_image'
	waifu2x.lua:291: in function 'waifu2x'
	waifu2x.lua:296: in main chunk
	[C]: in function 'dofile'
	...yang/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
	
By the way, when i run  th web.lua , the same error happens.

**Comment by nagadomi** [comment]
`-model_dir` option is `./models/upconv_7/art` by default.
and `models/upconv_7/art/nosie1_model.t7` is symbolic link to `models/vgg_7/art/noise1_model.t7`.
```
% ls -la models/upconv_7/art/noise1_model.t7 
lrwxrwxrwx 1 nagadomi nagadomi 31 Jul 21  2016 models/upconv_7/art/noise1_model.t7 -> ../../vgg_7/art/noise1_model.t7
```
so is symbolic link is broken? or could not read?

```
# OK
th waifu2x.lua -model_dir models/vgg_7/art -m noise -noise_level 1 -i 1.jpg -o output_image.png
# Error?
th waifu2x.lua -model_dir models/upconv_7/art -m noise -noise_level 1 -i 1.jpg -o output_image.png 
```

**Comment by yshua5631** [comment]
Thanks nagodomi @nagadomi , the reason is symbolic link, i fix it manually by run  ln -s /home/yang/study/waifu2x/models/vgg_7/  /home/yang/study/waifu2x/models/upconv_7,  it works.
I'm wondering that is there any script in waifu2x to create this link?

**Comment by nagadomi** [comment]
It will create by `git clone`.
Did you download source code from zip archive?
Perhaps your zip software does not support symbolic links.

**Comment by yshua5631** [comment]
Yes, i used zip archive, the reason seems clear now.

**Comment by nagadomi** [comment]
Thanks for the report. I didn't realize this issue.
