### ISSUE TITLE
Training - How does it work?

### ISSUE THREAD

**Issue by BrokenSilence** [nagadomi/waifu2x#17]
What would happen if I were to train it some more on 2x upscaling?
-Would it reset what it already trained?
-Or would it add improvment to the already trained 2x model?

Also, if I wanted to train it for 2.26218461x, would it work? or does it need to be 2, or 3x, and so on..?

**Comment by nagadomi** [comment]
1. replace "Box" filter with "Blackman" filter ( https://github.com/nagadomi/waifu2x/search?utf8=%E2%9C%93&q=Box)
2. remove `scale%2 == 0` assertion from code ( https://github.com/nagadomi/waifu2x/blob/master/lib/settings.lua#L46 ) 
3. train your own model
```
th train.lua -method scale -scale 2.26218461
# and 2.26218461 scaling
th waifu2x.lua -m scale -scale 2.26218461 -i input.png -o output.png
```
It might work. but I have not tested it.
In my experiment, Box filter + 2x scaling gives me best 2x quality but Box filter does not support 3x and 2.26218461x  scaling (it can but poor quality case).

**Comment by BrokenSilence** [comment]
I'm experimenting 2.25x scaling.. I only removed the lock on the mod 2..
I'll try later with the blackman filter.. and compare..

Now a cool and amazing feature would be to be able to gradually train it.. 
Like, train it with 100 images today, tomorrow another 100 different images, and so on..
I realize that will not be as easy, but it would be very beneficial..


Also maybe a bug, or maybe its my system's fault..
When converting data, it will increase the RAM usage to full. then it will start using the SWAP.. And also fill it up to max, after that everything just freezes in time..

I only have 8GB RAM, 3.8GB SWAP..
This was with 1500 images..

Should I increase the SWAP memory?
Or what do you have on your system?

**Comment by nagadomi** [comment]
convert_data.lua and train.lua require lots of RAM(16GB~32GB). The code is not efficient.  loading all uncompressed image to the RAM.
I have 32GB RAM.

**Comment by BrokenSilence** [comment]
But if I add 30 GB to the SWAP, maybe I can still do it.. Right?

**Comment by nagadomi** [comment]
Probably very slow.
