### ISSUE TITLE
noise factor

### ISSUE THREAD

**Issue by abrahamyan-lusine** [nagadomi/waifu2x#171]
Hi!
What kind of noise do You use in training, is this is a Gaussian noise or something else? And do You know is there any similar function in python?

**Comment by nagadomi** [comment]
noise in the context of waifu2x is JPEG artifact.
pseudocode:
```
noise_image = jpeg_decode(jpeg_encode(src_image, quality=100*(1 - noise_factor)))
```
PIL.Image supports JPEG encoder/decoder.

**Comment by abrahamyan-lusine** [comment]
And do You apply it after bluring, or before?

**Comment by nagadomi** [comment]
after.
In 2x + denoise training,
```
small_image = resize(src_image, 1/2)
small_noisy_image = jpeg_decode(jpeg_encode(small_image, quality=100*(1 - noise_factor)))
```
waifu2x does not use blur but uses resize.

**Comment by abrahamyan-lusine** [comment]
A follow Your steps, but cant achive such a noise reduction. Do You use some postprocessing ?

**Comment by nagadomi** [comment]
No. waifu2x uses only CNN.
