### ISSUE TITLE
Problems raised when a PNG image was being processed.

### ISSUE THREAD

**Issue by RikaSugisawa** [nagadomi/waifu2x#181]
When I tried to expand a PNG image with an alpha channel, somewhere translucent seemed unlikely to retain its transparency but more likely to transform into white background with other colors on it.

**Comment by RikaSugisawa** [comment]
If contributors have difficulties solving this problem, I'd like to know if I could do something on myself instead(such as with Photoshop).

**Comment by nagadomi** [comment]
Retaining alpha channel is already supported.
Are there still some problems with that?

example:
input:
![firefox-512](https://cloud.githubusercontent.com/assets/287255/24787398/0c0a3ff8-1ba3-11e7-8754-cf6b75312fc2.png)

output:
![firefox-512_waifu2x_art_scale_tta_1](https://cloud.githubusercontent.com/assets/287255/24787401/120cecde-1ba3-11e7-895c-43fd8729712d.png)

**Comment by RikaSugisawa** [comment]
I wonder when this function was added and whether this is supported in waifu2x-caffe? If not, I'd rather get an Ubuntu.

**Comment by RikaSugisawa** [comment]
Thanks. I think this should be my fault. This issue can be closed now.

**Comment by nagadomi** [comment]
OK, This was supported here. https://github.com/nagadomi/waifu2x/issues/29
waifu2x-caffe supports the same function (It's exactly the same algorithm). However waifu2x-caffe does not support grayscale PNG with alpha channel. Only RGBA PNG is supported.
