### ISSUE TITLE
[Question] luarocks install problem

### ISSUE THREAD

**Issue by RikaSugisawa** [nagadomi/waifu2x#182]
When I tried to:
`luarocks install graphicsmagick`

`luarocks install csvigo`

It just returned 
> Error: No results matching query were found.

I wonder if it's my fault.

**Comment by RikaSugisawa** [comment]
Also I couldn't found them when I tried to search.

**Comment by nagadomi** [comment]
Did you use luarocks that is installed by torch?
graphicsmagick and csvigo are only available on torch's rocks repo. https://github.com/torch/rocks

**Comment by RikaSugisawa** [comment]
It seems that I did something wrong. とてもありがとうございます。

**Comment by JSkalskiSBG** [comment]
@RikaSugisawa 
If you installed **luarocks** from debian repository it does not work (report that half of required packets do not exist).
First type:

    sudo apt remove luarocks

Then restart PC or run in terminal code that Torch added to **your user** .bashrc file ( **cat ~/.bashrc** ). In my case it was (linux user: jskalski ):

    . /home/jskalski/torch/install/bin/torch-activate

**Comment by JMH2198** [comment]
How do I use Torch's Luarocks?
