### ISSUE TITLE
504 /502 Error when converting images

### ISSUE THREAD

**Issue by Moonboy65** [nagadomi/waifu2x#187]
EDIT: added 502 error.
I get two things when trying to convert splash artwork from League of Legends:

![504 Gateway Time-out error](https://user-images.githubusercontent.com/14064784/27509559-39da6d48-58bd-11e7-86ec-db3929546e3c.png)

![502 Bad Gateway Error](http://puu.sh/wBODP/61c166c6eb.png)

Anyone know what might be causing this? I have always used waifu2x and i've never gotten any of these issues before.

Any help would be appreciated.

Notes: the 504 Error isn't as frequent, but the 502 Error is worse (not annoying but it's more on the terms of: what is causing the errors to happen).

**Comment by Moonboy65** [comment]
I also get the Bad Gateway error as well

**Comment by fartingbunny** [comment]
I'm having the same issue. Did the basics to see if it was my end causing the error and it wasn't. I can't convert anything since every single time I get a 502 error.

**Comment by DestinoAzell** [comment]
True since yesterday I have same problem.. I can't seem to convert anymore! HELP!

**Comment by edvakf** [comment]
I'm the maintainer of the site waifu2x.udp.jp. Let me take a look.

**Comment by Moonboy65** [comment]
thank you

**Comment by DestinoAzell** [comment]
@edvakf it's fine now thank you !

**Comment by Moonboy65** [comment]
@edvakf it's working!!!

what was causing the error?

**Comment by edvakf** [comment]
A task for deleting old cache was failing due to our Jenkins server maintenance, which caused no new docker image to start.

Thank you for reporting. It was very helpful. 
@nagadomi Can you please close this issue?

**Comment by Moonboy65** [comment]
the 502 error is back

**Comment by Moonboy65** [comment]
someone needs to keep watching the site when this happens

**Comment by Moonboy65** [comment]
502 Error keeps coming back, regardless of what happens, jenkins maintenance or not

**Comment by anonymau5** [comment]
It's pretty easy to setup your own once dependencies have been satisfied.  If you have any issues, look through the closed issues, I've ran into just about any issue you could have with installation.  This one runs on a 940M and is quick enough for my purposes. 

[](https://i.imgur.com/lNEkh1s.png)

**Comment by Moonboy65** [comment]
how did you do that?

**Comment by nagadomi** [comment]
I changed the cache storage to RAM. Probably that will reduce the server load.

**Comment by Moonboy65** [comment]
that's not the issue, changing to RAM did nothing, i just got the 502 error yet again
