### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by garrett** [nagadomi/waifu2x#2]
This is an amazing image rescaler.

How would one install it on typical Linux distros (such as Fedora, openSUSE, Ubuntu, from source, etc.)?

It would be great to have the instructions in the README.md file or on a separate page (but linked from the README).

**Comment by nagadomi** [comment]
added.

**Comment by BrokenSilence** [comment]
Would it be possible to run this on windows as well?

**Comment by nagadomi** [comment]
torch7 does not support windows :sob:
