### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by subnet-** [nagadomi/waifu2x#20]
I'm not quite fond with ubuntu and/or lua, does it work with windows? If yes, how?

**Comment by BrokenSilence** [comment]
https://github.com/nagadomi/waifu2x/issues/2

**Comment by nagadomi** [comment]
@WL-Amigo released waifu2x-converter-cpp.
waifu2x-converter-cpp supports windows and without GPU.
https://github.com/WL-Amigo/waifu2x-converter-cpp
https://github.com/WL-Amigo/waifu2x-converter-cpp/releases
