### ISSUE TITLE
Is this site provided by you?

### ISSUE THREAD

**Issue by Tao-kun** [nagadomi/waifu2x#200]
[Bigjpg](http://www.bigjpg.com/jp)

Is does not provide the copyright information of [waifu2x](https://github.com/nagadomi/waifu2x).

![](http://www.bigjpg.com/static/css/demo.png)

**Comment by nagadomi** [comment]
No. I only provide waifu2x.udp.jp .
waifu2x is an open source software, it is possible to create similar sites.
I also know http://waifu2x.me/ and http://waifu2x.booru.pics/.
In particular, waifu2x.me is displaing many ads on twitter and google, but it's not an official site, it's not related to me.
