### ISSUE TITLE
Odd problem with anime_style_art_rgb

### ISSUE THREAD

**Issue by xxprototypexx32** [nagadomi/waifu2x#203]
So I tried using the "anime_style_art_rgb" model to upscale and this happened: http://imgur.com/a/5q6oj
It also happens to "photo" but even darker
the one without "rgb" doesn't have this problem
Running on:
waifu2x-converter-cpp
OS X Sierra 10.12.6

**Comment by nagadomi** [comment]
I am not a developer of waifu2x-converter-cpp.
If the problem does not occur with our web service( http://waifu2x.udp.jp/ ), post the issue to the repository of waifu2x-conveter-cpp.
(waifu2x-conveter-cpp is currently maintained in the forked repo https://github.com/DeadSix27/waifu2x-converter-cpp )

**Comment by xxprototypexx32** [comment]
huh, well thanks for the quick reply
