### ISSUE TITLE
i can't upscaling image

### ISSUE THREAD

**Issue by richiejazon** [nagadomi/waifu2x#204]
hi..
why i can't upscaling image? please help me.. T_T

**Comment by nagadomi** [comment]
describe your issue in detail.

**Comment by richiejazon** [comment]
Yes,,
i want upscaling my image but, my image not upscaling, always conversion fails.. 
like this.. 

![1c](https://user-images.githubusercontent.com/31432649/29852174-d6071c64-8d62-11e7-8d22-14da752b1aed.jpg)

**Comment by nagadomi** [comment]
waifu2x.me is not our official web service.
We provide only http://waifu2x.udp.jp/
