### ISSUE TITLE
spatial convolution weight reshaped?

### ISSUE THREAD

**Issue by nickmen** [nagadomi/waifu2x#206]
Hi, I tried to load the model of upconv_7/art/noise3_scale2.0x_model.t7 and try to get the weight of the first spatial convolution by doing the command model:get(1).weight. However I notice the weight size dimension is 16x27. Shouldn't it be 16x3x3x3? How do i reshape that to 16x3x3x3? Appreciate any help. Thank you.

**Comment by nagadomi** [comment]
https://github.com/nagadomi/waifu2x/blob/a1458de3c86de4e6d7860ff8922607b235e3097d/tools/export_model.lua#L52

**Comment by nickmen** [comment]
Thank you, nagadomi!
