### ISSUE TITLE
error: invalid request

### ISSUE THREAD

**Issue by fartingbunny** [nagadomi/waifu2x#207]
This problem started today.

I'll upload an image, check the captcha, and then when I hit convert I'm led to an image that states "Error: Invalid Request" with a link to waifu2x beneath it. I can repeatedly clear the captcha until it finally gives me the image I'm trying to convert, but it takes anywhere from three to seven tries to get my image instead of the error.

**Comment by nagadomi** [comment]
Fixed. waifu2x.udp.jp is running on two api servers, but one of them had a problem.
