### ISSUE TITLE
Difficulty downloading images with transparency

### ISSUE THREAD

**Issue by ROMaster2** [nagadomi/waifu2x#211]
Browser: Firefox

If a picture is uploaded through http://waifu2x.udp.jp/, Ctrl+S to save it often downloads the `Error: Invalid Request` image. This is mostly alright for images with no transparent background as it's easy to copy and paste it into either Paint or Photoshop and save that way, but if the image has a transparent layer, clipboard copies with it a black background.

**Comment by nagadomi** [comment]
Use 'Download' button.

**Comment by ROMaster2** [comment]
That was hidden from me from a CSS problem on my end :/
