### ISSUE TITLE
Question about training data

### ISSUE THREAD

**Issue by 201101050424** [nagadomi/waifu2x#219]
Could you please provide the 6000-image dataset?

**Comment by nagadomi** [comment]
No. I won't provide it.

**Comment by leeqiaogithub** [comment]
> No. I won't provide it.

So, can you tell me what data set you're using？or just a general description.

**Comment by nagadomi** [comment]
Crawled image data(sites like danbooru) filtered by image resolution and lossless image format(+manually remove fake PNG format).

**Comment by leeqiaogithub** [comment]
> Crawled image data(sites like danbooru, I made this in 2012) filtered by image resolution and lossless image format(+manually remove fake PNG format).

I got it.thanks
