### ISSUE TITLE
404 error while trying to convert

### ISSUE THREAD

**Issue by fartingbunny** [nagadomi/waifu2x#221]
Trying to convert an image leads to a page titled 404 Not Found. The "site", however, is called Lansinoh. I've attached an image to show you what's appearing for me.

![screen shot 2018-01-24 at 9 49 17 am](https://user-images.githubusercontent.com/29925623/35341781-134d23d2-00ec-11e8-8a8f-36c274000ae0.png)

**Comment by nagadomi** [comment]
rebooted.
see https://github.com/nagadomi/waifu2x/issues/197#issuecomment-320363076
