### ISSUE TITLE
Fails to run on Cuda 9.2

### ISSUE THREAD

**Issue by anonymau5** [nagadomi/waifu2x#234]
All modules compile correctly, all steps go smoothly.  When running the web.lua, it crashes saying the cuda version is insufficient.  Now this could be a Torch issue not supporting 9.2 which I'll create a thread there if one doesn't already exist.

user@Nagisa:~/waifu2x$ th web.lua 
THCudaCheck FAIL file=/home/user/torch/extra/cutorch/lib/THC/THCGeneral.c line=70 error=35 : CUDA driver version is insufficient for CUDA runtime version
/home/user/torch/install/bin/luajit: /home/user/torch/install/share/lua/5.1/trepl/init.lua:389: lib/w2nn.lua:18: Failed to load CUDA modules. Please check the CUDA Settings.
---
/home/user/torch/install/share/lua/5.1/trepl/init.lua:389: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /home/user/torch/extra/cutorch/lib/THC/THCGeneral.c:70
stack traceback:
	[C]: in function 'error'
	/home/user/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	web.lua:7: in main chunk
	[C]: in function 'dofile'
	...user/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

**Comment by nagadomi** [comment]
I have not tried CUDA 9.2 yet.
>CUDA driver version is insufficient for CUDA runtime version

This error may appear when the driver version is old or the installation has failed.
Have you installed GPU driver compatible with CUDA 9.2 and reboot?

**Comment by anonymau5** [comment]
I am running version 396 of the nvidia driver.  A reboot has also happened prior to creating this ticket.  I have purged and reinstalled Cuda, the Nvidia driver, torch, and waifu2x twice just to make sure. 
Everything builds fine without error.

**Comment by nagadomi** [comment]
I have installed CUDA 9.2. It worked with the same steps as #222. I think your issue is caused by the driver installation.

**Comment by anonymau5** [comment]
I'll have to look back into it.  The machine it was on has run into issues from all the changes happening trying to get it to work.

**Comment by anonymau5** [comment]
On another machine it seems to be working fine.  The original machine installation may be broken.
