### ISSUE TITLE
GraphicsMagick 

### ISSUE THREAD

**Issue by Archit01** [nagadomi/waifu2x#237]
I have installed luarocks GraphicsMagick 
But when  running th waifu2x.lua 
Its showing 
gm (graphicsmagick) binary not found please install (see www.graphicsmagick.org) 
images/miku_small_ noise_scale.png 0.434.. sec 
I have Ubuntu 17.10 
Installed latest cuda 9.2
Torch and everything described in guide 
I did sudo to install graphicsmagick 
Because without sudo it's not installing showing error not found 

How to fix although it seems waifu2x is working as I tested with upscaling and it gave output 
But always showing graphicsmagick not found 
Will it effect training models ?

**Comment by nagadomi** [comment]
It is an error from graphicsmagick/convert.lua(wrapper to GraphicsMagick (binary)).
waifu2x does not use it.
That error is displayed when `which gm` command fails. gm is command line interface for graphicsmagick. If waifu2x is working, libgraphicsmagick (shared library for graphicsmagick) is installed, but command line tool is not installed.

**Comment by Archit01** [comment]
Thanks for the support 
I did sudo apt install graphicsmagick 
And it does not show any error now
