### ISSUE TITLE
Does this model have two function in one model? [high resolution/denoise]

### ISSUE THREAD

**Issue by DevKiHyun** [nagadomi/waifu2x#242]
I know that this waifu 2x model is inspired SRCNN model.
And, I know that this waifu 2x model have denoising fucntion not only have high resolution upscaling.
Did I understand right? If I understood it correctly, did this model train with low-resolution images and noise images?

**Comment by nagadomi** [comment]
Yes. waifu2x has three types of tasks.

- noise_scale: upscaling with denoising.
- scale: upscaling only.
- noise: denoising only.

noise_scale model is trained with low-resolution(downsampling) and noise(JPEG compression) images -> original high resolution image.

**Comment by DevKiHyun** [comment]
In summary, this model is a single model and its structure is srcnn. Also, low-resolution images and noise images by jpeg compressing were simultaneously learned as learning data. Did I understand correctly?

**Comment by nagadomi** [comment]
>its structure is srcnn

Currently, the CNN structure of waifu2x is not the same as SRCNN paper.
SRCNN was published in 2014, before VGG Net was published. While I was developing waifu2x, CNN/Deep Learning developed rapidly, so I used a some technique that was released later. VGG Net, LeakyReLU, Deconvolution layer.

**Comment by DevKiHyun** [comment]
ok. thanks!
