### ISSUE TITLE
Has this model been trained in Ycbcr space?

### ISSUE THREAD

**Issue by DevKiHyun** [nagadomi/waifu2x#243]
In super resolution problem, most model trained image data set on Ycbcr space. Also, we can train them in the rgb space as well. So I wondered which space you trained the image. If you have been training in both spaces, I want you to let me know where you got better results.

**Comment by nagadomi** [comment]
The oldest model `models/vgg_7/art_y` is trained in YUV space(Y only, chroma is upscaling by lanczos). Other models are trained in RGB sapce. However, the loss of R, G, B elements is weighted based on luminance of YUV (0.299 × R + 0.587 × G + 0.114 × B).
RGB is slightly better. And waifu2x supports JPEG denoising, so we can repair JPEG chroma sampling with all channels.

**Comment by DevKiHyun** [comment]
Good, But the difference of performance between RGB  3 channel and only Y channel of  YUV or Ycbcr is not noticeabley different, then is not only-Y-channel learning more resource efficient than RGB channel learning?

**Comment by nagadomi** [comment]
In my opinion, there is no big difference in performance/resource because only input layer and output layer are changed. There will be a difference when increasing the number of parameters in hidden layers.

**Comment by DevKiHyun** [comment]
ok, thanks!
