### ISSUE TITLE
Use TTA Mode with OpenCL?

### ISSUE THREAD

**Issue by nightingale1975** [nagadomi/waifu2x#245]
Hello,

unfortunately, I have a little problem to use waifu2x-caffe, because I use Intel HD Graphic via windows and not Nvidia, so it isn´t possible for me to use Cuda.
But I read, with OpenCL there would be another way, to use the GPU, but don´t know, if I could us waifu2x-caffe with it.
I would appreciate every little hint.

And thank you very much in advance.
nightingale

**Comment by nagadomi** [comment]
https://github.com/DeadSix27/waifu2x-converter-cpp supports OpenCL but it does not support latest waifu2x model.

**Comment by nightingale1975** [comment]
Thank you very much.
I realized a little bit too late, that it would be also possible to run it with the CPU.
It lasts pretty long, but it doesn´t matter, because, it is such a wonderful little program and I can´t thank you enough for your efforts, which you invested in this project.:)

Dear Greetings
nightingale

**Comment by nagadomi** [comment]
Thank you
