### ISSUE TITLE
i can't start the programm because file is .sln and i ain't any programm to open it with, but

### ISSUE THREAD

**Issue by ShiZZe225** [nagadomi/waifu2x#248]
2 months ago i could use it with no problem, i simply opened .exe file and i could start work, but now as i downloaded it again it shows me the same file as .sln file and i can't start the application.
and i have the same problem with all other projects on github also.

**Comment by nagadomi** [comment]
wrong post? I have never distributed exe in this repository.

Or are you mentioning waifu2x-caffe?
If so, you should download the file from the release tab.
https://github.com/lltcggie/waifu2x-caffe/releases (waifu2x-caffe.zip)
