### ISSUE TITLE
Error on demo page

### ISSUE THREAD

**Issue by Xaekai** [nagadomi/waifu2x#25]
Failed to load resource: the server responded with a status of 405 (Method Not Allowed)

**Comment by nagadomi** [comment]
I think its your browser's issue.
Can you check in google chrome?

**Comment by Xaekai** [comment]
I was using Chromium.

**Comment by nagadomi** [comment]
In my machine, Demo page works fine in Chromium(Version 41.0.2272.76 Ubuntu 14.04 (64-bit)).

**Comment by nagadomi** [comment]
/api does not support GET request.  Please do not reload a result page.

**Comment by Xaekai** [comment]
I never once reloaded the page.

But its ok. I figured it out. It was the [Image Viewer](https://chrome.google.com/webstore/detail/image-viewer/kcljlcpbfbkapegpifkodjdmdllgdlmk?hl=en) extension.

**Comment by BrokenSilence** [comment]
I use the same Extension, and I dont have any problems..
