### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by nguyenanduong** [nagadomi/waifu2x#265]
First, special thank to the creator. Such a great tool!
I am currently encountering a problem with slightly larger images. With image size of 1688x2550, waifu2x crashed with Out of memory error. I am using AWS EC2's g2.2xlarge instance with 15GB RAM.
Any recommendation would be very appreciated

**Comment by nagadomi** [comment]
Did you convert 1688x2550 images with batch mode (`-l` option)?  [I do not think that waifu2x will use more than 15GB RAM for 1688x2550 single image]
If so, garbage collection may be the cause.
https://github.com/nagadomi/waifu2x/blob/128222332b7967123de0dd186dd75a4dfdfa640f/waifu2x.lua#L237-L239

```lua
	 --if i % 10 == 0 then
	    collectgarbage()
	 --end
```
Commenting out as above will free up memory for each image conversion.

**Comment by nguyenanduong** [comment]
I got the same error when converting the single image. Worth mentioning that it's png exported from GIMP. Do you suggest jpeg input instead?
Thanks

**Comment by nagadomi** [comment]
I've tested on g2.2xlarge instance. The cause of the error is GPU out of memory, not RAM.
An easy solution is to use the `-crop_size 192` option (`-crop_size 256` by default).
Another solution is to use cuDNN or to use g3 instance.

**Comment by nguyenanduong** [comment]
That makes sense. Let me try g3 instance with more GPU memory
Thanks a lot for support!
