### ISSUE TITLE
Processing semi-transparent pngs

### ISSUE THREAD

**Issue by williammalo** [nagadomi/waifu2x#27]
When trying to process semi-transparent pngs, a white background is added.
I have a project where I need to upscale images, and waifu2x is the only algorithm that looks good enough, but unfortunately, I can't use it for semi-transparent image :(

**Comment by nagadomi** [comment]
I fixed this issue and updated the demo-application.

**Comment by williammalo** [comment]
great! I'm so happy!!! you are doing a great service to mankind

**Comment by leilei-** [comment]
Thanks.  I had to use an annoying imagemagick-based workaround of splitting the alpha to a separate image for Waifu2x to process in a batch

**Comment by nagadomi** [comment]
My implementation is similar to ImageMagick solution. 
The alpha channel is scaled with generic image scaler.

**Comment by nagadomi** [comment]
Fixed #29
