### ISSUE TITLE
IO error

### ISSUE THREAD

**Issue by llamasking** [nagadomi/waifu2x#279]
Whenever I try to use waifu2x.lua, I get an IO error. Between the time I last used waifu2x, which it worked just fine then, and now was moving my $home directory. I have since tried reinstalling torch. If anyone has an idea, may they please help? This happens across the board with any image. 

Console output (gist) because formatting:
https://gist.github.com/llamasking/0d2dd4e84255ad8d813c0ba16fb1db9a

**Comment by nagadomi** [comment]
My guess is that `./output` already exists and is a directory.
Specify the output filename for the `-o` option.
```
th waifu2x.lua -i images/city.jpg -o output_filename.png
```

**Comment by llamasking** [comment]
I'm stupid. Thank you!
