### ISSUE TITLE
waifu2x is down

### ISSUE THREAD

**Issue by sadisticdonut** [nagadomi/waifu2x#286]
Error 1009 Ray ID: 4ea378115c636bf6 • 2019-06-21 05:09:12 UTC
Access denied
What happened?
The owner of this website (egg.5ch.net) has banned the country or region your IP address is in (US) from accessing this website.

is this just down for me?

**Comment by nagadomi** [comment]
I guess that the waifu2x's server is down and IP address was being reused by other sites.
5ch.net is a famous forum in Japan and it is not related to waifu2x.

**Comment by nagadomi** [comment]
Oh, I link to 5ch.net on the error page. It is a thread about waifu2x on 5ch.net. no worries.
