### ISSUE TITLE
waifu2x doesn't handle transparency properly

### ISSUE THREAD

**Issue by williammalo** [nagadomi/waifu2x#29]
### Examples:

Expected Result
![good](https://cloud.githubusercontent.com/assets/1521848/8187062/d676dfee-141b-11e5-99a2-9170cf60c563.png)
Actual Result
![bad](https://cloud.githubusercontent.com/assets/1521848/8187065/dd47633e-141b-11e5-9d71-a4afe50bbcf2.png)
To get the example image with good transparency, I ran waifu2x on the image over a black background and over a white background and compared the two with a filter. This proves that waifu2x does work properly if the background isn't semi-transparent

Original image:
![sapling_spruce-white](https://cloud.githubusercontent.com/assets/1521848/8187260/ea86a1da-141c-11e5-8a13-97ad5bc20b0d.png)

**Comment by nodegin** [comment]
If I understand correctly you want to keep the edges crispy?
Why you not just resize it with PS / GIMP by Nearest Neighbor?

**Comment by williammalo** [comment]
@nodegin that would make the image pixellated :)

**Comment by Archeia** [comment]
This is also an issue for me as well. It was super fun converting old game assets that I had lost files over, but the sadness of making them transparent was :(

**Comment by Saren-Arterius** [comment]
I think waifu2x is not good at pixelated image scaling...
Maybe you would want to try 2xSAI?

**Comment by PwnicornDev** [comment]
I can confirm this, it doesn't have to do with pixellation in the original.
In the first example, the edges are blurred where they are flanked by transparent areas. In the second example I added a white background prior to upscaling, resulting in perfectly clean edges.

![1411945581847](https://cloud.githubusercontent.com/assets/3987812/8929498/3e92d904-3526-11e5-8265-34a49104cb54.png) ![7292df9f-ac9d-40fe-c0aa-e56ea5e29d97](https://cloud.githubusercontent.com/assets/3987812/8929515/68f13150-3526-11e5-8bed-9536949465f5.png)
![1411945581847_](https://cloud.githubusercontent.com/assets/3987812/8929542/8e9c87b0-3526-11e5-86bc-cbdc3012fd91.png) ![6c18f7de-9a8f-4d45-cd52-db186355d56a](https://cloud.githubusercontent.com/assets/3987812/8929544/93ab1c8a-3526-11e5-934c-764f28bb2f0e.png)

**Comment by internetakias** [comment]
Not sure if this is worth mentioning, but earlier versions of waifu2x-caffee could produce transparent images with sharp edges.

**Comment by PwnicornDev** [comment]
@internetakias Do you know an exact version where it was working? If we can find the commit that broke it, we should be able to solve it easily.

**Comment by internetakias** [comment]
@PwnicornDev
1.0.5 is the last version that produced scales with proper transparency.

**Comment by internetakias** [comment]
Hey @nagadomi, you haven't replied to this issue yet so I want to ask you if there's a way to fix this.

**Comment by nagadomi** [comment]
The latest version slightly improves for this issue but still not enough.
I think this issue is very difficult to solve for various cases. (semi transparent or fully transparent, for white background color or black background color)
Sorry, I am pending it.

**Comment by internetakias** [comment]
I understand. Thanks for replying and keep up the good work!

**Comment by nagadomi** [comment]
I fixed this issue. try http://waifu2x.udp.jp/ 

![83d9f6de-1d55-4a43-ca9e-9c9da71e9353](https://cloud.githubusercontent.com/assets/287255/11500230/1d8a0ef6-986f-11e5-9971-87b7b07b845a.png)

**Comment by andreili** [comment]
Sory, reopen issue...
Original image with alpha-channel:
![01-00-a00-007sek a](https://cloud.githubusercontent.com/assets/1331777/14668136/2580c376-06d2-11e6-9ca8-0eac61ce564c.PNG)
Upscaled image (x2, without denoise):
![01-00-a00-007sek a](https://cloud.githubusercontent.com/assets/1331777/14668149/3d468dce-06d2-11e6-8aa0-078c50da280c.PNG)
Transparent space become opaque, which increased the size.
The game has a lot of images, and this problem increases its size by 50-60Gb = /

**Comment by nagadomi** [comment]
How is waifu2x supposed to do?
I think it is problem of an original image that has unreasonably large transparent area.

**Comment by andreili** [comment]
Unfortunately, it is a feature of the original game, and such areas should be.
Under the program - it does not have to process the field with 100% transparency. Now she treats them as a whole, which significantly increases the processing time:
```
./images/./Event01/01-00/01-00-A01/01-00-A01-015.PNG: 2.3339378833771 sec
./images/./Event01/01-00/01-00-A01/01-00-A01-015SET.A.PNG: 4.6067349910736 sec
./images/./Event01/01-00/01-00-A01/01-00-A01-015SET.B.PNG: 4.6801130771637 sec
./images/./Event01/01-00/01-00-A01/01-00-A01-015SET.C.PNG: 4.6291019916534 sec
```
(The first - the background, the rest - imposed on the background image with transparency, similar to the above).

**Comment by nagadomi** [comment]
I fixed that file size problem.
![alpha_2x2](https://cloud.githubusercontent.com/assets/287255/14671318/2cc460e8-072c-11e6-9fb2-6de4fba7f73d.png)

before fix: 740888 bytes
after fix:    37333 bytes

And, if image has alpha channel, 2x process time is required. alpha channel upscaling with waifu2x improves the upscaling result in some case.
see: https://twitter.com/mhhpnvu/status/673488043735539712

**Comment by andreili** [comment]
Yes, the local version has updated and checked.
Thanks for the quick response.
