### ISSUE TITLE
Can noise reduction be set to be intermediate to the fixed noise_level settings?

### ISSUE THREAD

**Issue by sjscotti** [nagadomi/waifu2x#294]
I have images where noise_level set at 0 is not enough, but when set at 1 it is too much filtering.  Is it possible to have an intermediate amount of noise reduction between noise_level 0 and 1?
Thanks!

**Comment by nagadomi** [comment]
No. Each noise_level uses a different pre-trained model.

**Comment by sjscotti** [comment]
Ok, thanks for the speedy response. 


--------------------------------------------------------------------
A person who never made a mistake never tried anything new. -- Albert Einstein

Well done is better than well said. -- Benjamin Franklin

The essence of faith is fewness of words and abundance of deeds. -- Bahá´u´lláh

--------------------------------------------------------------------
