### ISSUE TITLE
Can't get torch compiled

### ISSUE THREAD

**Issue by slayerduck** [nagadomi/waifu2x#296]
I'm upgrading my server with 2x 2080ti GPU's and i did a fresh install of centos 7, i compiled the way i did before with torch7 and CUDA 9.2. There seems to be some sort of bug, maybe incompatibility of CUDA 9.2 with the latest 2080ti GPU. When i run th waifu2x it just hangs and does nothing, monitoring nvidia-smi shows the waifu very slowly filling up GPU mem at like 5MB/s. After a couple min i just kill the process because its pointless. 

So then i attempted to install CUDA 10.0 and also tried 10.1, then using your https://github.com/nagadomi/distro repo to install the modified version of torch. But sadly i can't seem to get it compiled correctly.

Found CUDA on your machine. Installing CUDA packages

Warning: unmatched variable LUALIB

jopts=$(getconf _NPROCESSORS_CONF)

echo "Building on $jopts cores"
cmake -E make_directory build && cd build && cmake .. -DLUALIB= -DLUA_INCDIR=/home/waifu/torch/install/include -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/waifu/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/waifu/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$jopts install

Building on 24 cores
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/waifu/torch/install
-- Found CUDA: /usr/local/cuda (found suitable version "10.1", minimum required is "6.5")
CMake Error at /home/waifu/torch/install/share/cmake/torch/FindCUDA/select_compute_arch.cmake:42 (if):
  if given arguments:

    "CUDA_VERSION" "VERSION_GREATER_EQUAL" "7.0"

  Unknown arguments specified
Call Stack (most recent call first):
  /home/waifu/torch/install/share/cmake/torch/FindCUDA.cmake:1042 (include)
  CMakeLists.txt:7 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/waifu/torch/extra/cutorch/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.

I wasn't sure if i should make the issue here or on your other repo, would you be able to assist me?

**Comment by nagadomi** [comment]
hmm, VERSION_GREATER_EQUAL syntax seems to require CMake 3.7 or later.

**Comment by nagadomi** [comment]
fixed https://github.com/nagadomi/distro/commit/95bb31825091dbe7ba7d3dd11501f7d808b82a17
It should work on older cmake.

**Comment by slayerduck** [comment]
Thank you for your help! I downloaded the updated torch from the repo and encountered a different error.

Found CUDA on your machine. Installing CUDA packages
Warning: unmatched variable LUALIB

jopts=$(getconf _NPROCESSORS_CONF)

echo "Building on $jopts cores"
cmake -E make_directory build && cd build && cmake .. -DLUALIB= -DLUA_INCDIR=/home/waifu/torch/install/include -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/waifu/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/waifu/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$jopts install

Building on 24 cores
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/waifu/torch/install
-- Found CUDA: /usr/local/cuda (found suitable version "10.1", minimum required is "6.5")
-- Removing -DNDEBUG from compile flags
-- TH_LIBRARIES: TH
-- MAGMA not found. Compiling without MAGMA support
CMake Error at /home/waifu/torch/install/share/cmake/torch/FindCUDA/select_compute_arch.cmake:145 (string):
  string does not recognize sub-command APPEND
Call Stack (most recent call first):
  /home/waifu/torch/install/share/cmake/torch/FindCUDA/select_compute_arch.cmake:173 (CUDA_DETECT_INSTALLED_GPUS)
  lib/THC/CMakeLists.txt:121 (CUDA_SELECT_NVCC_ARCH_FLAGS)


CMake Error at /home/waifu/torch/install/share/cmake/torch/FindCUDA/select_compute_arch.cmake:145 (string):
  string does not recognize sub-command APPEND
Call Stack (most recent call first):
  /home/waifu/torch/install/share/cmake/torch/FindCUDA/select_compute_arch.cmake:173 (CUDA_DETECT_INSTALLED_GPUS)
  lib/THC/CMakeLists.txt:121 (CUDA_SELECT_NVCC_ARCH_FLAGS)


-- Autodetected CUDA architecture(s):
-- got cuda version 10.1
-- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
-- CUDA_NVCC_FLAGS: -D__CUDA_NO_HALF_OPERATORS__;-DCUDA_HAS_FP16=1
-- THC_SO_VERSION: 0
-- Performing Test HAS_LUAL_SETFUNCS
-- Performing Test HAS_LUAL_SETFUNCS - Failed
-- Configuring incomplete, errors occurred!
See also "/home/waifu/torch/extra/cutorch/build/CMakeFiles/CMakeOutput.log".
See also "/home/waifu/torch/extra/cutorch/build/CMakeFiles/CMakeError.log".

Error: Build error: Failed building.

**Comment by nagadomi** [comment]
It's also a cmake version issue, your cmake seems older than I guess (is it 2.8?).
fixed https://github.com/nagadomi/distro/commit/c77e2fe355def79241412c698140169281aee4ac, but I'm not sure if there is any other issue. I can't test with that old cmake.

**Comment by slayerduck** [comment]
New version compiled without errors, the bug i had while compiled with CUDA 9.2 before no longer is there so it does seem there is some issues with the old CUDA and latest videocards maybe? 

Anyway, thanks for the bug fixes! This is resolved.
