### ISSUE TITLE
Selecting GPU, zombie process?

### ISSUE THREAD

**Issue by slayerduck** [nagadomi/waifu2x#298]
I never had a multiple GPU's in one system but I'm trying to force waifu2x to specific GPU's and spawn threads on both of them to load balance between them. When i use the -gpu option and select 1 or 2 it does appear to load the process correctly on one GPU but leave a sort of zombie process on the other GPU. See screenshot:
https://prntscr.com/ouvwbf

If repeated they stack processes:
http://prntscr.com/ouw3r2

**Comment by nagadomi** [comment]
Does it happen when you run waifu2x.lua/web.lua on the command line then CTRL+C?
waifu2x.lua/web.lua does not use multiprocessing. So I think zombie process is your process management code issue.

**Comment by slayerduck** [comment]
I run "th waifu2x.lua -m noise_scale -noise_level 1 -force_cudnn 1 -i test.png -o test_up.png -gpu 2" from command line. I also tried running th waifu2x.lua without any other arguments and it still spawns the two processes on each GPU. nvidia-smi shows the same PID as seen on the screenshots i send.

**Comment by nagadomi** [comment]
The first screenshot is normal. CUDA will try to initialize all detected GPUs.
If you really want to use only one GPU, specify `CUDA_VISIBLE_DEVICES` environment variable. and when you specify `CUDA_VISIBLE_DEVICES`, always use `-gpu 1` option.
example:
```
CUDA_VISIBLE_DEVICES=0 th waifu2x.lua -gpu 1 # use GPU 0
CUDA_VISIBLE_DEVICES=1 th waifu2x.lua -gpu 1 # use GPU 1
```
Note that `CUDA_VISIBLE_DEVICES` is 0 origin(start from 0), `-gpu` option is 1 origin.
