### ISSUE TITLE
Cannot run in CUDA10.0 + cuDNN

### ISSUE THREAD

**Issue by cppfred** [nagadomi/waifu2x#299]
Before I install CUDA10.0 and CUDNN I can still use it. After install CUDA,it will crash each time i use.Error Tips is " cudaSuccess (10 vs. 0)  invalid device ordinal".Plz fix it, thx!

**Comment by nagadomi** [comment]
Did you rebuild torch7 for CUDA10? and installed a GPU driver that supports CUDA10?

>invalid device ordinal

This error occurs when the GPU device cannot be used from CUDA.

**Comment by cppfred** [comment]
I just fix the problem of drivers
But after I fix it I still cannot use it normally, then I use NVIDIA Nsight to check all the process that waifu2x used, and I found that all the process in GPU was not use my GTX1070 (GPU No.1) at all, it use my GPU No.0 (Intel UHD 630), which is inside my CPU.
But before run this programe I already set using GPU No.1 ... I dont know what happend.

**Comment by cppfred** [comment]
I just solve the problem right now
I set GPU No.0 and it work ... doesnt it mean GPU number in Windows Task manager？

**Comment by nagadomi** [comment]
If you are using code from this repository, use the `-gpu 2` option.
Even with other software, there is probably an option to specify the GPU ID to use.
GPU ID has 1 origin(start from 1) and 0 origin(start from 0) depending on the software.

**Comment by cppfred** [comment]
Thanks help me solve the problem!!(*^▽^*)
