### ISSUE TITLE
Web.lua does not work

### ISSUE THREAD

**Issue by slayerduck** [nagadomi/waifu2x#3]
Successfully installed everything, i can use the command line to convert images but the web gui errors out

[root@waifu2x waifu2x-master]# th web.lua
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init.lua:363: /root/torch/install/share/lua/5.1/trepl/init.lua:363: /root/torch/install/share/lua/5.1/trepl/init.lua:363: /usr/local/share/lua/5.1/turbo/epoll_ffi.lua:69: bad argument #1 to 'new' (size of C type is unknown or too large)
stack traceback:
        [C]: in function 'error'
        /root/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
        web.lua:4: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x004064d0

**Comment by nagadomi** [comment]
try upgrade luajit version to 2.0.4.
http://luajit.org/download.html

**Comment by slayerduck** [comment]
I'm already running 2.0.4

**Comment by nagadomi** [comment]
hmm.. seems turbo.lua failed to detecting your platform.
maybe following patch fixes this issue.
edit file: turbo/turbo/platform.lua (https://github.com/kernelsauce/turbo/blob/master/turbo/platform.lua#L30)
```
    __ABI32__ = false, -- true if your platform is i386
    __ABI64__ = true, -- true if your platform is x86-64
```
and reinstall.
if you need more support, please create a issue in turbo (https://github.com/kernelsauce/turbo)

**Comment by slayerduck** [comment]
After changing that and recompiling i get this:

/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init.lua:363: /root/torch/install/share/lua/5.1/trepl/init.lua:363: /usr/local/share/lua/5.1/turbo/util.lua:351: Could not load libtffi_wrap
        Please run makefile and ensure that installation is done correct.
stack traceback:
        [C]: in function 'error'
        /root/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
        web.lua:4: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x004064d0

**Comment by Saren-Arterius** [comment]
I am getting this too.

**Comment by nagadomi** [comment]
try
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
th web.lua
```

**Comment by slayerduck** [comment]
Works, can be closed thanks!

TIP: add the line export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib to your .bashrc

**Comment by FantasyJXF** [comment]
I met the error `Could not load libtffi_wrap`


> try
> 
> ```
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
> th web.lua
> ```

This doesn't work on my case.

My Env:
* CentOS 7.3
* GPU V100 with driver 410.129
* CUDA 10

After I install turbo with `luarocks`, the output is :
```
==== Installing libtffi_wrap ====
test -f libtffi_wrap.so && \
install -m 0755 libtffi_wrap.so /home/work/torch/install/lib/libtffi_wrap.so.2.1.0 && \
ldconfig -n /home/work/torch/install/lib && \
ln -sf libtffi_wrap.so.2.1.0 /home/work/torch/install/lib/libtffi_wrap.so
==== Successfully installed Turbo.lua 2.1.0 to /home/work/torch/install ====
Updating manifest for /home/work/torch/install/lib/luarocks/rocks
turbo 2.1-2 is now built and installed in /home/work/torch/install/ (license: Apache 2.0)
```
I notice that my `libtffi_wrap.so` was located in `$HOME/torch/install/lib` not `/usr/lib`

**Comment by nagadomi** [comment]
Run
```
~/torch/install/bin/torch-activate
```
This script adds `~/torch/install/lib` to `LD_LIBRARY_PATH`.
Also, this script is registered in ~/.bashrc or ~/.zshrc when installing torch, so it will be automatically applied once you login again.

**Comment by FantasyJXF** [comment]
Thanks

---
From Fantasy
