### ISSUE TITLE
nn/Sequential.lua:29: bad argument #1 (field padW does not exist) on Arch Linux

### ISSUE THREAD

**Issue by VBChunguk** [nagadomi/waifu2x#30]
I've installed Torch7 with [torch/distro](https://github.com/torch/distro), which also installed lots of luarocks including `cutorch`, `cunn`, and `graphicsmagick`. The compilation and installation went well with proper dependencies. The installation directory is `/home/vbchunguk/torch/install/`.

With previous version(the cuDNN version), it exited with error because I don't have cuDNN-compatible GPU. Now waifu2x doesn't need cuDNN anymore, so I tried to run waifu2x again, with hope. But the error occured:

    $ primusrun th waifu2x.lua
    /home/vbchunguk/torch/install/bin/luajit: .../vbchunguk/torch/install/share/lua/5.1/nn/Sequential.lua:29: bad argument #1 (field padW does not exist)
    stack traceback:
        [C]: in function 'updateOutput'
        .../vbchunguk/torch/install/share/lua/5.1/nn/Sequential.lua:29: in function 'forward'
        /home/vbchunguk/waifu2x/lib/reconstruct.lua:19: in function 'reconstruct_layer'
        /home/vbchunguk/waifu2x/lib/reconstruct.lua:45: in function 'image'
        waifu2x.lua:36: in function 'convert_image'
        waifu2x.lua:116: in function 'waifu2x'
        waifu2x.lua:121: in main chunk
        [C]: in function 'dofile'
        ...nguk/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x00405be0

I'm using GeForce GT 520M(CUDA compute capability 2.1) on laptop, and I used `primusrun` because the laptop is using Optimus. Is there a problem with not using Ubuntu?

**Comment by nagadomi** [comment]
Try update nn and cunn package.
This could be caused by version mismatch between cunn and nn.

**Comment by VBChunguk** [comment]
I've updated `cunn`, but not `nn`. I updated `nn` and it worked well. Thanks!
