### ISSUE TITLE
Waifu2x Libretro port and a shader-based version.

### ISSUE THREAD

**Issue by ADormant** [nagadomi/waifu2x#31]
Is it possible to make a libretro/RetroArch version? For this It may be necessary to create a CG/GLSL version?
https://github.com/libretro/RetroArch/wiki
https://github.com/libretro/common-shaders

**Comment by nagadomi** [comment]
GLSL version can be found at https://github.com/ueshita/waifu2x-converter-glsl .
However, waifu2x filter is very slow. I think waifu2x is not suitable for shader in game.

**Comment by ADormant** [comment]
@nagadomi Okay I just found some optimized versions http://forum.videohelp.com/threads/372157-New-upscaling-algorithm-waifu2x .
https://github.com/lltcggie/waifu2x-caffe
Even if it is slow it's still worth to give it a shot, RetroArch has dozens of different cores and not only gaming ones. Could you try to port it to RetroArch's shader spec?

**Comment by nagadomi** [comment]
I won't do it individually.

**Comment by ADormant** [comment]
So I understand there're some technical difficulties? Well, maybe someone will notice this issue and try.

**Comment by leilei-** [comment]
realtime neural network scalers are no way feasible.

**Comment by ADormant** [comment]
Well look at that serration reduction. https://github.com/hrydgard/ppsspp/issues/7796
