### ISSUE TITLE
[Question] Is it possible to scale an image to a specific resolution in the CL version?

### ISSUE THREAD

**Issue by wafflesinmybauble** [nagadomi/waifu2x#313]
As the title says, I was wondering if it's at all possible to scale an image to specific resolution. The reason being, I need to make the resolution of the images 1:1 Ex: 1024x1024 but the original resolutions are not 1:1, rather they are uneven ratios. If this isn't already possible via the CL, could it be implemented?

**Comment by nagadomi** [comment]
See https://github.com/nagadomi/waifu2x/issues/275#issuecomment-478448765

**Comment by wafflesinmybauble** [comment]
I figured this out when I gave it some thought. In any case, this will help with the SEO of this program. Thank you anyways. Closing.
