### ISSUE TITLE
Cuda9.0; waifu2x cannot work sometimes

### ISSUE THREAD

**Issue by BERYLSHEEP** [nagadomi/waifu2x#315]
my cuda version is 9.0.
I test the command "th waifu2x" is  ok.
But when I try to process my image.
some images upscale well but somes failed. Can somebody help me?

local:1/13/100%/2.3s /home/beryl/Documents/Anime-Face-Dataset-master/animeface-character-dataset/thumb/000_hatsune_miku/face_858_187_45.png
/tmp/cLKyVf.png: 0.7607090473175 sec	
local:1/14/100%/2.2s /home/beryl/Documents/Anime-Face-Dataset-master/animeface-character-dataset/thumb/000_hatsune_miku/face_136_245_126.png
THCudaCheck FAIL file=/home/beryl/torch/extra/cutorch/lib/THC/THCGeneral.c line=70 error=38 : no CUDA-capable device is detected
/home/beryl/torch/install/bin/luajit: /home/beryl/torch/install/share/lua/5.1/trepl/init.lua:389: /home/beryl/Documents/waifu2x/lib/w2nn.lua:52: Failed to load CUDA modules. Please check the CUDA Settings.

/home/beryl/torch/install/share/lua/5.1/trepl/init.lua:389: cuda runtime error (38) : no CUDA-capable device is detected at /home/beryl/torch/extra/cutorch/lib/THC/THCGeneral.c:70
stack traceback:
	[C]: in function 'error'
	/home/beryl/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	/home/beryl/Documents/waifu2x/waifu2x.lua:5: in main chunk
	[C]: in function 'dofile'
	...eryl/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406510
convert-im6.q16: improper image header `/tmp/OCLNXN.png' @ error/png.c/ReadPNGImage/3954.
convert-im6.q16: no images defined `/home/beryl/Documents/Anime-Face-Dataset-master/animeface-character-dataset/thumb/000_hatsune_miku/face_136_245_126.png' @ error/convert.c/ConvertImageCommand/3258.

**Comment by nagadomi** [comment]
>no CUDA-capable device is detected

Does this error happens randomly? It is a fatal error. I think there is a problem with the graphics driver or hardware. If it happens only during long-term processing, it may be GPU overheating.

Also, if your shell script calls `th waifu2x.lua` in a loop, using batch conversion(`-l` option) can reduce the load.  https://github.com/nagadomi/waifu2x#batch-conversion

**Comment by BERYLSHEEP** [comment]
I am still confusing.
I test "th waifu2x" is ok in waifu2x directory.
`(base) beryl@beryl-System-Product-Name:~/Documents/waifu2x$ th waifu2x.lua
images/miku_small_noise_scale.png: 0.24784207344055 sec`

but when i try this script in outside directory. Cuda is no dectected.
`. ~/torch/install/bin/torch-activate
upscaleWaifu2x() {
    SIZE1=$(identify -format "%h" "$@")
    SIZE2=$(identify -format "%w" "$@");

    if (( $SIZE1 < 512 && $SIZE2 < 512  )); then
        echo "$@" $SIZE
        TMP=$(mktemp "/tmp/XXXXXX.png")
        CUDA_VISIBLE_DEVICES="$((RANDOM % 2 < 1))" nice th ~/Documents/waifu2x/waifu2x.lua -model_dir \
            ~/Documents/waifu2x/models/upconv_7/art -tta 1 -m scale -lua -scale 2 \
            -i "$@" -o "$TMP"
        convert "$TMP" "$@"
        rm "$TMP"
    fi;  }

export -f upscaleWaifu2x`

`(base) beryl@beryl-System-Product-Name:~/Documents/Anime-Face-Dataset-master/animeface-character-dataset/thumb$ find 000_hatsune_miku/ -type f | parallel --progress --jobs 9 upscaleWaifu2x
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.


Computers / CPU cores / Max jobs to run
1:local / 12 / 9

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
local:9/8/100%/0.0s 000_hatsune_miku/face_447_216_121.png
THCudaCheck FAIL file=/home/beryl/torch/extra/cutorch/lib/THC/THCGeneral.c line=70 error=38 : no CUDA-capable device is detected
/home/beryl/torch/install/bin/luajit: /home/beryl/torch/install/share/lua/5.1/trepl/init.lua:389: /home/beryl/Documents/waifu2x/lib/w2nn.lua:52: Failed to load CUDA modules. Please check the CUDA Settings.
---
/home/beryl/torch/install/share/lua/5.1/trepl/init.lua:389: cuda runtime error (38) : no CUDA-capable device is detected at /home/beryl/torch/extra/cutorch/lib/THC/THCGeneral.c:70
stack traceback:
	[C]: in function 'error'
	/home/beryl/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	/home/beryl/Documents/waifu2x/waifu2x.lua:5: in main chunk
	[C]: in function 'dofile'
	...eryl/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406510
convert-im6.q16: improper image header `/tmp/hbGLv4.png' @ error/png.c/ReadPNGImage/3954.
convert-im6.q16: no images defined `000_hatsune_miku/face_447_216_121.png' @ error/convert.c/ConvertImageCommand/3258.
local:9/9/100%/0.0s 000_hatsune_miku/face_250_136_15.png
THCudaCheck FAIL file=/home/beryl/torch/extra/cutorch/lib/THC/THCGeneral.c line=70 error=38 : no CUDA-capable device is detected
/home/beryl/torch/install/bin/luajit: /home/beryl/torch/install/share/lua/5.1/trepl/init.lua:389: /home/beryl/Documents/waifu2x/lib/w2nn.lua:52: Failed to load CUDA modules. Please check the CUDA Settings.
---
/home/beryl/torch/install/share/lua/5.1/trepl/init.lua:389: cuda runtime error (38) : no CUDA-capable device is detected at /home/beryl/torch/extra/cutorch/lib/THC/THCGeneral.c:70
stack traceback:
	[C]: in function 'error'
	/home/beryl/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	/home/beryl/Documents/waifu2x/waifu2x.lua:5: in main chunk
	[C]: in function 'dofile'
	...eryl/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406510
convert-im6.q16: improper image header `/tmp/7dd5AW.png' @ error/png.c/ReadPNGImage/3954.
convert-im6.q16: no images defined `000_hatsune_miku/face_250_136_15.png' @ error/convert.c/ConvertImageCommand/3258.
local:9/10/100%/0.0s 000_hatsune_miku/face_128_326_108.png
THCudaCheck FAIL file=/home/beryl/torch/extra/cutorch/lib/THC/THCGeneral.c line=70 error=38 : no CUDA-capable device is detected
/home/beryl/torch/install/bin/luajit: /home/beryl/torch/install/share/lua/5.1/trepl/init.lua:389: /home/beryl/Documents/waifu2x/lib/w2nn.lua:52: Failed to load CUDA modules. Please check the CUDA Settings.
---
/home/beryl/torch/install/share/lua/5.1/trepl/init.lua:389: cuda runtime error (38) : no CUDA-capable device is detected at /home/beryl/torch/extra/cutorch/lib/THC/THCGeneral.c:70
stack traceback:
	[C]: in function 'error'
	/home/beryl/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	/home/beryl/Documents/waifu2x/waifu2x.lua:5: in main chunk
	[C]: in function 'dofile'
	...eryl/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406510
convert-im6.q16: improper image header `/tmp/JCEw8j.png' @ error/png.c/ReadPNGImage/3954.
convert-im6.q16: no images defined `000_hatsune_miku/face_128_326_108.png' @ error/convert.c/ConvertImageCommand/3258.
local:9/11/100%/0.1s 000_hatsune_miku/face_568_250_96.png
THCudaCheck FAIL file=/home/beryl/torch/extra/cutorch/lib/THC/THCGeneral.c line=70 error=38 : no CUDA-capable device is detected
/home/beryl/torch/install/bin/luajit: /home/beryl/torch/install/share/lua/5.1/trepl/init.lua:389: /home/beryl/Documents/waifu2x/lib/w2nn.lua:52: Failed to load CUDA modules. Please check the CUDA Settings.
---
/home/beryl/torch/install/share/lua/5.1/trepl/init.lua:389: cuda runtime error (38) : no CUDA-capable device is detected at /home/beryl/torch/extra/cutorch/lib/THC/THCGeneral.c:70
stack traceback:
	[C]: in function 'error'
	/home/beryl/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	/home/beryl/Documents/waifu2x/waifu2x.lua:5: in main chunk
	[C]: in function 'dofile'
	...eryl/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406510
convert-im6.q16: improper image header `/tmp/0SxcAO.png' @ error/png.c/ReadPNGImage/3954.
convert-im6.q16: no images defined `000_hatsune_miku/face_568_250_96.png' @ error/convert.c/ConvertImageCommand/3258.
local:9/12/100%/0.1s 000_hatsune_miku/face_363_253_144.png
	
	
Usage: [options]

waifu2x
Options:
  -i           path to input image [images/miku_small.png]
  -l           path to image-list.txt []
  -scale       scale factor [2]
  -o           path to output file [(auto)]
  -depth       bit-depth of the output image (8|16) [8]
  -model_dir   path to model directory [./models/cunet/art]
  -name        model name for user method [user]
  -m           method (noise|scale|noise_scale|user) [noise_scale]
  -method      same as -m []
  -noise_level (0|1|2|3) [1]
  -crop_size   patch size per process [256]
  -batch_size  batch_size [1]
  -resume      skip existing files (0|1) [0]
  -thread      number of CPU threads [-1]
  -tta         use TTA mode. It is slow but slightly high quality (0|1) [0]
  -tta_level   TTA level (2|4|8). A higher value makes better quality output but slow [8]
  -force_cudnn use cuDNN backend (0|1) [0]
  -q           quiet (0|1) [0]
  -gpu         Device ID [1]
  -load_mode   ascii/binary [ascii]
`

**Comment by nagadomi** [comment]
>CUDA_VISIBLE_DEVICES="$((RANDOM % 2 < 1))"

Is CUDA available on both GPU0 and GPU1? (And the output value range of this expression differs between `sh` and `bash`(or `zsh`))
When this environment variable is incorrect, `no CUDA-capable device is detected` error will happen.
```
CUDA_VISIBLE_DEVICES=0 th waifu2x.lua 
CUDA_VISIBLE_DEVICES=1 th waifu2x.lua 
```

And, `-lua` is an undefined option.

**Comment by BERYLSHEEP** [comment]
Thanks a lot! Yes, i found cuda is only available on GPU0 in my computer.
