### ISSUE TITLE
Questions about channel identity LBP loss

### ISSUE THREAD

**Issue by kice** [nagadomi/waifu2x#316]
https://github.com/nagadomi/waifu2x/blob/3613450386688cb2082407476b23f8d24169233d/lib/LBPCriterion.lua#L12-L18

I think you want to create an identity for input channels (pixelwise loss), but this section only make identity for the first channel.

```lua
if i == 1 then
    -- identity for input channels of first layer
    for j = 1, ch do
        filter.weight[j]:fill(0)
        filter.weight[j][j][math.floor(k/2)+1][math.floor(k/2)+1] = 1
    end
end
```

where `filter.weight[i]` change into `filter.weight[j]`, use `j` instad of `i`, which always is `1` after the if conditation.

**Comment by nagadomi** [comment]
You are right. This is an embarrassing bug. Fixed.
However, I think there is almost no difference in practice.
