### ISSUE TITLE
[Suggestion] Batch Conversion+Downloadable Version

### ISSUE THREAD

**Issue by radzo73** [nagadomi/waifu2x#323]
Hey, been using Waifu2X for a while, and it is amazing.
However, there's been times when I've wanted to convert a bunch of images, only to go to the website, upload a file, solve the CAPTCHA, wait for it to convert, then download the file. Is there a way to let us upload multiple files to convert all at once?

Also, I have no idea how to run the releases on my computer. I open index.html like any other web document, insert a file, and then it redirects me to C://api, even though it should go to Me/Wherever waifu2x is/waifu2x.lua

**Comment by Kadantte** [comment]
For multiple pictures, it will be a pain in the ass for the server so this is why there's the Captcha.
For the release it's not how it works you need to read the documentation how you run it by your self not just open the index.html and you're ready. Go to [Installation](https://github.com/nagadomi/waifu2x#installation).

**Comment by nagadomi** [comment]
If you are a windows user, I recommend you to use [waifu2x-caffe](https://github.com/lltcggie/waifu2x-caffe)(Just download from `releases` tab) or [waifu2x-ncnn-vulkan](https://github.com/nihui/waifu2x-ncnn-vulkan).
The code of this repo only work on Linux or MacOS, and it supports [batch conversion](https://github.com/nagadomi/waifu2x#batch-conversion) on local machine.
