### ISSUE TITLE
This is literally the most impossible program to install

### ISSUE THREAD

**Issue by JMH2198** [nagadomi/waifu2x#325]
I'm on Ubuntu. I have everything I need for this to work. I have installed, and reinstalled your fixed torch many times, but it still won't work. I try to run `th waifu2x.lua` at the directory where Waifu2x is installed and I get this: 

`/usr/bin/luajit: /usr/share/lua/5.1/trepl/init.lua:389: lib/w2nn.lua:52: Failed to load CUDA modules. Please check the CUDA Settings.
/usr/share/lua/5.1/trepl/init.lua:389: /usr/share/lua/5.1/trepl/init.lua:389: module 'torch' not found:
	no field package.preload['torch']
	no file 'lib/torch.lua'
	no file './torch.lua'
	no file '/usr/share/luajit-2.1.0-beta3/torch.lua'
	no file '/usr/local/share/lua/5.1/torch.lua'
	no file '/usr/local/share/lua/5.1/torch/init.lua'
	no file '/usr/share/lua/5.1/torch.lua'
	no file '/usr/share/lua/5.1/torch/init.lua'
	no file './torch.so'
	no file '/usr/local/lib/lua/5.1/torch.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/torch.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/usr/share/lua/5.1/trepl/init.lua:389: in function 'require'
	waifu2x.lua:5: in main chunk
	[C]: in function 'dofile'
	/usr/lib/torch-trepl/th:149: in main chunk
	[C]: at 0x560d28adb1d0`

If I run the same command in my home directory, I get this: 

`/usr/bin/luajit: cannot open waifu2x.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	/usr/lib/torch-trepl/th:149: in main chunk
	[C]: at 0x56417b5c71d0`

Someone please help me, I'm at my wit's end here.

**Comment by nagadomi** [comment]
>Failed to load CUDA modules. Please check the CUDA Settings

Have you installed CUDA and NVIDIA driver?

>/usr/bin/luajit
>/usr/lib/x86_64-linux-gnu/lua/5.1/torch.so

The torch7 distro that I released is not installed in the system directory, it is installed in the home directory (`${HOME}/torch`).
I don't know how you installed it in the system directory, but I think you need to uninstall it first.

**Comment by JMH2198** [comment]
I have installed CUDA 10 on my computer via apt. Where exactly in the system directory should I install torch?
