### ISSUE TITLE
Image error using CUnet and denoise only

### ISSUE THREAD

**Issue by VireV** [nagadomi/waifu2x#338]
I was looking to denoise a very noisy image using waifu2x. Obviously, the image is way too noisy to get any good output from but I did it anyway. The original image:

![ESzKB3RUwAEHZoV](https://user-images.githubusercontent.com/57366614/76421125-19135700-639b-11ea-88cd-23f74e8bf424.png)

The results from other models seemed to give poor results so I tried the CUnet model. However, when I did, the output produced very distorted: 

This is with denoise only and set to level 1:
![ESzKB3RUwAEHZoV(CUnet)(noise)(Level1)](https://user-images.githubusercontent.com/57366614/76421222-43651480-639b-11ea-8489-4c5f29840975.png)

This is with denoise only and set to level 2:
![ESzKB3RUwAEHZoV(CUnet)(noise)(Level2)](https://user-images.githubusercontent.com/57366614/76421229-45c76e80-639b-11ea-9f86-450e0b27a0a5.png)

Is this a problem with the model itself or a bug elsewhere in the program?

Thank you.
(I am using waifu2x-caffe)

**Comment by nagadomi** [comment]
This is not the waifu2x-caffe's repository. It is https://github.com/lltcggie/waifu2x-caffe

>Is this a problem with the model itself or a bug elsewhere in the program?

There is no distortion problem with my implementation http://waifu2x.udp.jp/ .
When using CUNet model, `Split size` must be a multiple of 4. Try 128 or 64.

**Comment by VireV** [comment]
Sorry about that, I'll close it now.
