### ISSUE TITLE
Images with transparent background turn into fully colored images

### ISSUE THREAD

**Issue by Pierrounator** [nagadomi/waifu2x#347]
Hi~

I did a batch script to execute your script on a whole folder

```bat
SET waifu2x=C:\Users\drzoi\Documents\_GAYMU\[JEUX]\waifu2x-converter\waifu2x-converter.exe
SET waifuModels=C:\Users\drzoi\Documents\_GAYMU\[JEUX]\waifu2x-converter\models\
MKDIR "2x"
FOR %%i IN (*.*) DO CALL "%waifu2x%" --jobs 8 --scale_ratio 2.0 --input_file %%i --output_file ".\2x\%%i" --model_dir %waifuModels%
```

Unfortunately, for **.png** files with transparent background, I get a full colored image

![exit_02](https://user-images.githubusercontent.com/14140656/82360687-0d32b980-9a0a-11ea-8c8b-39f4cf17ed0e.png)

![exit_02](https://user-images.githubusercontent.com/14140656/82360723-16238b00-9a0a-11ea-959e-e474f8d9cc77.png)

Did I do something wrong?

**Comment by nagadomi** [comment]
My implementation supports transparent background. http://waifu2x.udp.jp/
I don't know which software you are using, but it's not developed by me.

**Comment by Pierrounator** [comment]
Oh god yes... I don't know where I found the version I had but yours works like a charm~

Sorry for the inconvenience!
