### ISSUE TITLE
Fatal Error has occured, possibility split size is too large

### ISSUE THREAD

**Issue by Beckerin0** [nagadomi/waifu2x#348]
While using any conversion mode, a popup showing "A fatal error has occurred. There is a possibility the split size is too large" no matter what split size I actually use. It has worked before in the past but just recently it has been having this issue. 

Split Size 1 not working
![image](https://user-images.githubusercontent.com/60204264/83822254-5da24c00-a685-11ea-966f-abaecde380bf.png)

Split size 128 not working (my default size)
![unknown (26)](https://user-images.githubusercontent.com/60204264/83822523-21bbb680-a686-11ea-8114-c1782223d963.png)

**Comment by nagadomi** [comment]
See https://github.com/lltcggie/waifu2x-caffe/issues/193

**Comment by Beckerin0** [comment]
After changing my GPU number from 0 to 1 it still was not working, but while using GPU 1, I changed my processor from CUDA to CPU. I don't really know what this does but it has fixed my problem. Thank you for responding as quickly as you did and here is what my change was.
![waifu2x fix](https://user-images.githubusercontent.com/60204264/83895708-ef529d80-a707-11ea-989e-bfd4e4e0841b.png)
After changing this, the program is now very slow, but I am happy that I am able to use it again.
![unknown (27)](https://user-images.githubusercontent.com/60204264/83895983-51ab9e00-a708-11ea-984a-69f3ec9f90f9.png)

**Comment by nagadomi** [comment]
If you have an NVIDIA GPU(Video Card), try split size 48 with CUDA.

**Comment by Beckerin0** [comment]
CUDA is turned on with split size 48. GPU 0 and GPU 1 don't seem to be changing anything
![unknown (28)](https://user-images.githubusercontent.com/60204264/83928120-7b35eb00-a743-11ea-928e-522d0425b139.png)

**Comment by nagadomi** [comment]
Check `error_log_*.txt`. It should be in the same folder as the exe file.

**Comment by Beckerin0** [comment]
I don't see an error log? Do you have another way of contact that you could do, if this is bothering you, the back and forth posting/commenting.
![unknown (29)](https://user-images.githubusercontent.com/60204264/83928884-32cbfc80-a746-11ea-9f33-9e84174e137c.png)

**Comment by nagadomi** [comment]
No. And I'm not the developer of that software.
other possible reasons:
1. Try changing Model to `2D illust (UpRGB Model)` (CUnet model needs a lot of VRAM)
2. Video card driver is outdated (NVIDIA driver should be updated)
3. Video card does not support CUDA (not made by NVIDIA or very old)

**Comment by Beckerin0** [comment]
2D illust fixed it, thank you so much!

**Comment by nagadomi** [comment]
>2D illust fixed it

In that case, your video card is out of VRAM that CUNet needs.
UpRGB works with less VRAM and is faster, but the quality is slightly lower than CUNet.
