### ISSUE TITLE
get this working for Fedora 32

### ISSUE THREAD

**Issue by Alfieri** [nagadomi/waifu2x#351]
Hi,

this is not a real issue. I have try to get this running on Fedora 32 and at the end it runs but it toke me 3 days of work. So I created this [Github repo](https://github.com/Alfieri/waifu2x-fedora) with my steps and some help links to get this working faster.

@nagadomi I did not know where the best place is to put these infos (README or Wiki). Can you do this, please?

**Comment by nagadomi** [comment]
I'm not going to link all waifu2x related articles, but the wiki can be edited by anyone.
I also publish torch.distro with CUDA 10 support  https://github.com/nagadomi/distro . I think this will make installation easier.

**Comment by Alfieri** [comment]
Ok then I will add this to the Wiki.
I understand your point you can not link all releated that are to many and as result you will have a repo full of links.

But my intention was to complete your installation section in your README. Why do you don't link to your torch7 repo if there are any fixes, which helps to get this working? I found your repo also after I was done and CUDA 10 was not the problem. The problem was to find a gcc version to compile torch7 with CUDA, because CUDA is only supported for a gcc version less then 8.

Anywhy this is not a real issue so I will close it.
