### ISSUE TITLE
Doesn't work properly under wsl2

### ISSUE THREAD

**Issue by CarbonPool** [nagadomi/waifu2x#354]
![wsl_test](https://user-images.githubusercontent.com/26106045/90888838-8ff05980-e3e9-11ea-9643-e3fac61f6e7f.png)
I am not sure whether cuda can work normally under wsl2. I should have completed the necessary dependency compilation. This is some error message: Failed to load CUDA modules. Please check the CUDA Settings.

**Comment by Dunge** [comment]
How did you manage to install cuda-toolkit-10-2 on wsl2? As far as I see, NVIDIA only provide "WSL-Ubuntu" distributions for Cuda11 and over, and using Cuda 9 or 10 will try to install nvidia drivers and screw your WSL installation.
