### ISSUE TITLE
Turbo Build Error

### ISSUE THREAD

**Issue by anonymau5** [nagadomi/waifu2x#36]
When installing the turbo luarocks package I get the following output.

Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/turbo-1.1-5.rockspec...
Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/turbo-1.1-5.rockspec... switching to 'build' mode
Cloning into 'turbo'...
remote: Counting objects: 162, done.
remote: Compressing objects: 100% (158/158), done.
remote: Total 162 (delta 15), reused 92 (delta 2), pack-reused 0
Receiving objects: 100% (162/162), 635.76 KiB | 0 bytes/s, done.
Resolving deltas: 100% (15/15), done.
Checking connectivity... done.
Note: checking out 'b4404dce73284f9e0d6d10e5df5bd198dff5a66f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Warning: variable CFLAGS was not passed in build_variables
make -C deps/http-parser library
make[1]: Entering directory '/tmp/luarocks_turbo-1.1-5-7996/turbo/deps/http-parser'
gcc -I. -DHTTP_PARSER_STRICT=0  -Wall -Wextra -Werror -O3  -fPIC -c http_parser.c -o libhttp_parser.o
gcc  -shared -Wl,-soname=libhttp_parser.so.2.1 -o libhttp_parser.so.2.1 libhttp_parser.o
make[1]: Leaving directory '/tmp/luarocks_turbo-1.1-5-7996/turbo/deps/http-parser'
gcc -Ideps/http-parser/ -shared -fPIC -O3 -Wall -g deps/http-parser/libhttp_parser.o deps/turbo_ffi_wrap.c -o libtffi_wrap.so -lcrypto -lssl
In file included from deps/turbo_ffi_wrap.c:32:0:
deps/turbo_ffi_wrap.h:33:25: fatal error: openssl/ssl.h: No such file or directory
 #include <openssl/ssl.h>
                         ^
compilation terminated.
Makefile:68: recipe for target 'all' failed
make: *** [all] Error 1

Error: Build error: Failed building.
 
I have checked and openssl is installed.

**Comment by nagadomi** [comment]
did you install *-dev package?
```
sudo apt-get install libssl-dev 
```

**Comment by anonymau5** [comment]
I had not, that fixed it.
