### ISSUE TITLE
Bloated File Size

### ISSUE THREAD

**Issue by anonymau5** [nagadomi/waifu2x#37]
I might be missing something here but when I compare the completed file in the cache folder with the one the API lets me download, I find that on average the file size is at least four times larger on the downloaded image.  If I open the downloaded image and save it again in GIMP it closely matches the filesize of the completed file in the cache folder.

**Comment by nagadomi** [comment]
In my machine, downloaded file is bit smaller than cache file.
This issue is maybe caused by the default PNG compression level of graphicsmagick.
I will fix it.

**Comment by anonymau5** [comment]
Thank you.
