### ISSUE TITLE
Is Waifu2x down?

### ISSUE THREAD

**Issue by naomoo55** [nagadomi/waifu2x#377]
When I tried to upscale my image and when it opens api page it says "405 Not Allowed".
Sometimes when I reload index page it says that waifu2x is down.

**Comment by XuanrTruc** [comment]
Sadly, I'm pretty sure it is. This happened to me from yesterday...I really wants to support the server, but as a student; I can't do it T-T

**Comment by That-Mac-Daddy** [comment]
it appears to be up at http://waifu2x.udp.jp/

**Comment by nagadomi** [comment]
waifu2.udp.jp is sometimes down. #197
