### ISSUE TITLE
waifu2x.udp.jp is down

### ISSUE THREAD

**Issue by Katsunya** [nagadomi/waifu2x#380]
Hey, the website waifu2x.udp.jp is down. I'm not sure if it's maintained by the same that answered back in 2019, but I found this place via Google and wanted to know if anyone could help out.

**Comment by RABIDYOTE** [comment]
It's down for me too. It's been like that since at least 3am EST. :(

**Comment by nagadomi** [comment]
The server has been re-started.
See #197 for more information about the server
