### ISSUE TITLE
Question about quality (closed)

### ISSUE THREAD

**Issue by LTGM** [nagadomi/waifu2x#385]
Hi,

I am using latest version of waifu-caffe and I wonder if there any difference between that and 'official' w2x?

I also wonder if there will be any updates in the future that may improve quality of deblocking/denoising/upscaling etc?
I wanted to upscale my whole gallery and I afraid there will be a better version coming out in the next few months or so and I will have to do that again (plus I will have to keep original files too...)

**Comment by nagadomi** [comment]
>I am using latest version of waifu-caffe and I wonder if there any difference between that and 'official' w2x?

waifu2x-caffe's cunet model is the same as the offical web app.

>I also wonder if there will be any updates in the future that may improve quality of deblocking/denoising/upscaling etc?

There are no planned updates so far.

**Comment by LTGM** [comment]
OK, thanks for the reply.
Last question tho: in your opinion waifu2x reached its peek level or there is a room for improvements in terms of quality (without introducing AI that draws the extra details like gigapixel)?
I don't really want to waste my time converting stuff and realize after I'm done there is a better and more efficient model available next day lol

**Comment by nagadomi** [comment]
>without introducing AI that draws the extra details like gigapixel

In my opinion, adding textures that aren't part of the original artwork is not a good idea.

**Comment by LTGM** [comment]
> > without introducing AI that draws the extra details like gigapixel
> 
> In my opinion, adding textures that aren't part of the original artwork is not a good idea.

I agree, that's why I said 'without'.

**Comment by nagadomi** [comment]
sorry for not fully understanding your views.
If the process can be made slower, it can be made better, but it increases the load on the web service.
In waifu2x-caffe, using TTA mode gives slightly better results, although it is 8 times slower.

**Comment by LTGM** [comment]
I use caffe mod in offline with TTA for better results so I don't stress the server. I just wonder if you will improve the quality of upscaling in the future or this implementation is the best we will get (because we can do only so much with limited amount of data we feed to waifu2x) :)

**Comment by nagadomi** [comment]
At least I'm not planning any improvements at the moment.

**Comment by LTGM** [comment]
OK, thanks
