### ISSUE TITLE
Error in RequestHandler

### ISSUE THREAD

**Issue by EarphonesGuy** [nagadomi/waifu2x#388]
This error seems to keep popping up every time I use it, it's never done this before so I'm not sure what it means:

<pre style="font-size:12px; font-family:monospace; color:#8B0000;">[web.lua]
Unknown error in RequestHandler, thread:
0x417bd478 is dead.
▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
__unnamed__ = &quot; 651\ 3\ 128\ 128\ [torch.LongStorage of size 4]\ &quot; stack traceback:
...&#47;ubuntu&#47;torch&#47;install&#47;share&#47;lua&#47;5.1&#47;turbo&#47;httpserver.lua:278: in function &lt;
...&#47;ubuntu&#47;torch&#47;install&#47;share&#47;lua&#47;5.1&#47;turbo&#47;httpserver.lua:255&gt; [C]: in function &#39;
xpcall&#39; &#47;home&#47;ubuntu&#47;torch&#47;install&#47;share&#47;lua&#47;5.1&#47;turbo&#47;iostream.lua:565: in function &lt;&#47;home&#47;ubuntu&#47;torch&#47;install&#47;share&#47;lua&#47;5.1&#47;turbo&#47;iostream.lua:556&gt; [C]: in function &#39;xpcall&#39; &#47;home&#47;ubuntu&#47;torch&#47;install&#47;share&#47;lua&#47;5.1&#47;turbo&#47;ioloop.lua:578: in function &lt;&#47;home&#47;ubuntu&#47;torch&#47;install&#47;share&#47;lua&#47;5.1&#47;turbo&#47;ioloop.lua:577&gt;
▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲</pre>

**Comment by nagadomi** [comment]
Does the waifu2x.lua command work?
```
th waifu2x.lua
```

**Comment by EarphonesGuy** [comment]
I apologize, I don't know much about the situation. May I ask, where or how I should use the command?

**Comment by nagadomi** [comment]
Is this problem about the waifu2x.udp.jp web service? If so, it may be a browser problem.
What OS and browser are you using? I think it will work with a common Chrome browser without AdBlock, etc.

**Comment by EarphonesGuy** [comment]
I use Chrome, yes, and I don't have an ad blocker installed.

I was using this version specifically "https://waifu2x.me/".

**Comment by nagadomi** [comment]
waifu2x.me is a website provided by a third party unrelated to me.

**Comment by EarphonesGuy** [comment]
Oh, I see, thank you for the help though.
