### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by anazelo21** [nagadomi/waifu2x#391]
I can't process the image.  always give "download error" and when I go to convert appears "error 502 in the getaway"
![Screenshot_2021-04-09-15-31-35-195_com android chrome](https://user-images.githubusercontent.com/77070677/114225457-b5b27a80-9948-11eb-81a7-4497e2a1e38a.jpg)
![Screenshot_2021-04-09-15-31-29-394_com android chrome](https://user-images.githubusercontent.com/77070677/114225459-b64b1100-9948-11eb-9796-bc0195ec8c6e.jpg)

**Comment by nagadomi** [comment]
https://github.com/nagadomi/waifu2x/issues/197#issuecomment-816986827
