### ISSUE TITLE
Getting errors

### ISSUE THREAD

**Issue by yogurtsmoothie10** [nagadomi/waifu2x#392]
When I try to 'convert' a photo I get the following page: 502 Bad Gateway nginx/1.10.3 (Ubuntu)
When I try to 'download' a photo I get this message: Download Error

I checked, and the photo is of the right size. I am doing the captcha. I've tried Google Chrome and Microsoft Edge so far (because I do not have any other browsers downloaded) and the results have been the same. I don't have an adblocker on ME, btw.

Any idea why this is happening?

**Comment by NaughtyMommy** [comment]
It's a problem on their end. You need to wait for them to fix the server.

**Comment by yogurtsmoothie10** [comment]
Got it, thank you!

**Comment by nagadomi** [comment]
https://github.com/nagadomi/waifu2x/issues/197#issuecomment-816986827
