### ISSUE TITLE
Denoise option on deepai?

### ISSUE THREAD

**Issue by jgoralcz** [nagadomi/waifu2x#394]
I am interested in automating about 200,000 images through the service provided on: https://deepai.org/machine-learning-model/waifu2x

However, I don't see the denoise option available. I'd only need the "low" setting for majority of the images.

Do you have another API I can work with or additional documentation for this API?

Or maybe there's another solution for automating all of these images (preferably not on my local machine or would be nice on a linux CPU only server)

**Comment by nagadomi** [comment]
I am not affiliated with deepapi in any way. 
If you don't have a GPU locally, an easy way is to rent a Spot Instance of `g4dn.xlarge` on EC2 and use [waifu2x-ncnn-vulkan](https://github.com/nihui/waifu2x-ncnn-vulkan) Linux binary. If you remember to shutdown the instance, you can use it for $0.16/h.
Also, you may be able to use a free GPU with Google Colab, but I haven't tried it.

**Comment by jgoralcz** [comment]
Ah thanks for the info.

By the way, it's deepai, not deepapi, and it says there's a verified account of "Nagadomi" on there.

I'll think of waifu2x-ncnn-vulkan. Any chance you know of a good docker image to work with this?

Thanks for the quick response btw. I appreciate it!

**Comment by nagadomi** [comment]
>verified account

I don't remember if I've logged in to deepai site, but at least I haven't created the API. It may be some kind of spoofing.

If you are familiar with Docker, there is a Docker image for this repo. (nagadomi on DockerHub is actually me :)
https://github.com/nagadomi/waifu2x#docker

**Comment by jgoralcz** [comment]
Thanks!
