### ISSUE TITLE
train.lua crashing with bad argument to torch.random()?

### ISSUE THREAD

**Issue by CMPXCHG8B** [nagadomi/waifu2x#40]
Greetings!

I'm trying to train my own networks, but it seems like pairwise_transform.lua is crashing on me when I try an image set consisting of images that aren't the same size (some are 256x256 pixels, some are 512x512 pixels, some are 1K and a few are 2K).

I get the following error right after I see "# make validation-set":

```
/Volumes/TORCH_SDK/usr/bin/luajit: bad argument #2 to '?' (upper bound must be larger than lower bound at /tmp/luarocks_torch-scm-1-2119/torch7/build/TensorMath.c:4546)
stack traceback:
	[C]: at 0x01d0f360
	[C]: in function 'random'
	.../Downloads/waifu_stuff/waifu2x/lib/pairwise_transform.lua:59: in function 'transformer'
	...even/Downloads/waifu_stuff/waifu2x/lib/minibatch_adam.lua:31: in function 'minibatch_adam'
	train.lua:121: in function 'train'
	train.lua:163: in main chunk
	[C]: in function 'dofile'
	...umes/TORCH_SDK/usr/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x0101baee70
```

If I make sure that all my input files are the exact same size (ie, 1K), then it seems to work (well, I think it is, it's happily running in the background right now and I can hear my GPU working up a sweat).

Is this a bug? Or is it a feature?

Cheers,
-CMPX

**Comment by nagadomi** [comment]
Yes this looks like a bug. width/height of image must be greater than 256+16px when crop_size=128(default).
Try 
```
th train.lua -random_half 0 ....
```
or
```
th train.lua -crop_size 96 ....
```

**Comment by CMPXCHG8B** [comment]
Ah, that makes sense.

Thanks for your help and the workaround!
