### ISSUE TITLE
[SUGGESTION] Possibly new translateables

### ISSUE THREAD

**Issue by Blueberryy** [nagadomi/waifu2x#402]
Can you add these to translateable list?
![chrome_WFs31Q2jME](https://user-images.githubusercontent.com/36592509/120672483-c811e600-c4ab-11eb-9786-aa1f75dc2186.png)
![chrome_9dYfavtNyz](https://user-images.githubusercontent.com/36592509/120672491-c9dba980-c4ab-11eb-9c99-4097e668f6e8.png)

**Comment by nagadomi** [comment]
It's a sentence contained only on my personal demo website(private branch), not in this repository.
I have no plans to include ads or patreon link in the command line tools or web interface of this repository.

**Comment by Blueberryy** [comment]
> It's a sentence contained only on my personal demo website(private branch), not in this repository.
> I have no plans to include ads or patreon link in the command line tools or web interface of this repository.

Oh okay
