### ISSUE TITLE
Wierd graphical error

### ISSUE THREAD

**Issue by kingfisherimperialist** [nagadomi/waifu2x#403]
waifu2x ver 1.2.0.3
cuDNN
win10
![Знімок екрана 2021-06-08 111141](https://user-images.githubusercontent.com/85549596/121148439-7326f480-c84a-11eb-9ace-638832715e61.png)

When Im trying to upscale this little Samuel, I get this wierd outcome. So far this behaviour is tied to this specific file, but editing it in paint or renaming doesnt help. Its not like I really need a fix, just interested what could cause such thing.

sorry for bad quality of the post

**Comment by nagadomi** [comment]
Setting the Split size to 128 or 100 will fix it. See https://github.com/lltcggie/waifu2x-caffe/issues/164 . 
Also, this is not a waifu2x-caffe repository. It's https://github.com/lltcggie/waifu2x-caffe .

**Comment by kingfisherimperialist** [comment]
thanks
