### ISSUE TITLE
What is this `th` command?

### ISSUE THREAD

**Issue by TornaxO7** [nagadomi/waifu2x#406]
In your readme, you're using this `th` command with `waifu2x.lua`:

```
th waifu2x.lua
```

how can I get this `th` command?

**Comment by nagadomi** [comment]
It is the lua interpreter command in Torch7. It is included in the Torch7 installation.

**Comment by TornaxO7** [comment]
Alright, thank you for the information! I'll look why I don't have it (although I installed python-torch?).
