### ISSUE TITLE
The background is blury

### ISSUE THREAD

**Issue by StockiChan** [nagadomi/waifu2x#414]
I dont know why this is happening but every objekt get blury that isnt near to the scene, or is this happening cause i have the free trial version?

**Comment by nagadomi** [comment]
Make sure you are posting in the right place.
I am not sure what the question means.

**Comment by StockiChan** [comment]
If there is a difference in the trial version and the patreon one

**Comment by nagadomi** [comment]
There is no trial or commercial version, there is only an open source version.
We are not providing anything special as a reward for patreon.
