### ISSUE TITLE
help

### ISSUE THREAD

**Issue by MrsLucifer** [nagadomi/waifu2x#423]
Can I run it as windows with .exe

and how can i install it on cpanel hosting.

**Comment by nagadomi** [comment]
>Can I run it as windows with .exe

use waifu2x-caffe or waifu2x-ncnn-vulkan.
https://github.com/lltcggie/waifu2x-caffe
https://github.com/nihui/waifu2x-ncnn-vulkan

>how can i install it on cpanel hosting.

I don't know.
