### ISSUE TITLE
Premium/pay version of the free website?

### ISSUE THREAD

**Issue by Leifman35** [nagadomi/waifu2x#426]
Hey @nagadomi , first and foremost THANK YOU for the amazing waifu2x.udp.jp. even if it is 'down' or not working right now it is definitely the best way to 'freely' use waifu2x on the web without actually doing it with your own hardware.

I've noticed you have a Patreon and i was really hoping and praying it might have some sorta tier for a 'paid/premium' usage of the website.. but that's not the case.

And i will explain what i mean by 'Premium/pay version', for example.. often i use the website waifu2x.me where i buy credits/pay $ to rent/use a dedicated server to do the waifu2x process for me (which for me is not upscaling but denoising) and i find it has certain benefits to it which i would have loved to somehow pay you to be able to use the website in that manner. it's not much really, mostly if there was a paid version of your website that has 1. No capche (as used as i got to it.. it would be nice to not have to keep doing it over and over for every file lol) 2. Multiple files/queuing numerous files 3. for the files to retain their original image name, just now as .png

I would definitely prefer to support you and spend my money on your website if it had such features/options instead of waifu2x.me. so i simply HAD to ask you about it. looking forward to hear from you.

**Comment by nagadomi** [comment]
I guess that not too many people would use it.
Also, the current free server costs about $500/month and patreon($183/month) does not cover the cost.
So I am not really motivated to improve the server environment.

If you often convert many images, I recommend getting an NVIDIA GPU and using the local version (waifu2x-caffe or waifu2x-ncnn-vulkan).

**Comment by Leifman35** [comment]
Unfortunately the 'do it yourself' using an NVIDIA GPU (which i have but no that 'newest kind' lol, a mere GTX 750 TI lol.. i know it's ancient) is not an option for me and i often either use your website or as i mentioned pay a few $ to 'rent' a Tesla V100 over at waifu2x-multi Pro which i'd have much preferred to pay u :D

But yeah i can understand your point of view. and while i can also pay a few $'s to ur patreon... i doubt it will make a difference as you mentioned yourself it doesn't even cover 50% of the costs. all that said, if you ever do somehow figure out to make a similar option to this website i already pay for, or maybe even simpler/a few more benefits to ppl that 'use your website quite a lot' then im more than willing to pay for it an switch to you.

**Comment by Leifman35** [comment]
oh and thank you for the reply. as i would really want to stress it that i ABSOLUTELY appreciate and can't thank you enough. you sir are a Hero in my eyes. Arigato Gozaimashta.
