### ISSUE TITLE
Filename gets truncated if it has a dot in it

### ISSUE THREAD

**Issue by ikasumi4u** [nagadomi/waifu2x#438]
Seen in the WebUI, the filename gets truncated if there's a dot in it. Seems it just takes the last dot in the filename, truncates it there, then appends the extension. Note the conversion tags (Waifu2x_art_, etc.) also do not get appended.

MyImage(...final).jpg → MyImage(...png

**Comment by nagadomi** [comment]
Fixed by https://github.com/nagadomi/nunif/commit/c6729f08448544043fde699e070a6e2a4992e253
waifu2x.udp.jp has also been updated.
