### ISSUE TITLE
[unlimited:waifu2x] Error: TypeError: Cannot read properties of null (reading 'run')

### ISSUE THREAD

**Issue by ryeager1979** [nagadomi/waifu2x#441]
This is on the new unlimited upscaler. Was working great until a couple days ago. Now whenever I do an upscales, i get this error: (-_-) Error: TypeError: Cannot read properties of null (reading 'run')

This is the link to the new one: https://unlimited.waifu2x.net/

Sorry if there is a better place to submit this, but I could not find it.

**Comment by nagadomi** [comment]
I think that is an error when the model file cannot be downloaded.
Did you have an Internet connection?
Try SHIFT + F5 or CTRL + F5 to reload.

It works in the browser, but the model file needs to be downloaded. Downloaded model files are cached for a few days but will expire.

**Comment by ryeager1979** [comment]
Sorry, I should have elaborated more: I am using the browser unlimited browser version +4x), when I select the file and then choose the output settings, I then hit 'start' and then this error prompts and no tile generation in the grey box happens. I have an active internet connection at the time.

**Comment by nagadomi** [comment]
No errors on my env.
Does it only happen with the specific file or mode?

Can you access this domain?
http://unlimited-cdn.waifu2x.net/

**Comment by ryeager1979** [comment]
Alright, issue appears to be completely on my end and I am guessing an issue with cookies or something. It is working with other browsers and in incognito mode on chrome. I don't know what could have caused it to start happening. If anyone else runs into this, I guess try another browsers/private mode first. Thank you for the prompt replies, I jumped on the patreon as a thanks :)

**Comment by nagadomi** [comment]
If it only happens when using a different browser, it could be a browser problem.
The following features are required for the current unlimited:waifu2x to work.
- WebAssembly
- Cross-Origin Resource Sharing

I have tested on the latest versions of Google Chrome and Firefox, but it may not work on older or less compatible browsers.

**Comment by nagadomi** [comment]
The model files are served from CloudFlare (CDN Provide), so it could be a problem there (there is extra processing such as attack and bot detection).
`unlimited-cdn.waifu2x.net` URL above is a domain on CloudFlare.

**Comment by ryeager1979** [comment]
I'm considering this "fixed" on my end, because I have a solution, but just to give you more information: 

It was working fine on Chrome for me, but then it suddenly stopped, leading to the issue that started this post. The last attempt I tried on Chrome Incognito, Firefox, and Brave, and those were successful. 

It still does not work on Chrome, but I haven't tried clearing my cache. I will just use incognito for now or another browser. 

The versions of Chrome I have tried and failed with are Version 109.0.5414.120 - Version 110.0.5481.78, with the second one being the latest version. 

The CloudFlare hosted CDN url also gives me that error on regular Chrome, even though I had obviously never visited it before. 

Again, I don't want you to spend anymore time then you have to for me, because I can get it to work on other browsers/incognito, but on regular chrome, it still does not work for me. I would think it is most likely a "me" problem.

**Comment by nagadomi** [comment]
Just now, I have moved `unlimited.waifu2x.net` domain to CloudFlare because Adsense has been approved.
At that time, an SSL/TLS configuration problem was causing ERR_TOO_MANY_REDIRECTS, so I fixed it.
Maybe the above problem has also been fixed.

**Comment by srbrandin-cpu** [comment]
same design and hd clear and clean design
