### ISSUE TITLE
Noise Reduction High Error

### ISSUE THREAD

**Issue by anonymau5** [nagadomi/waifu2x#45]
When selecting the high option in noise reduction the following is sent back via the web api.
Output after link due to GitHub field length restriction.
http://pastebin.com/GhLZYGzP

**Comment by nagadomi** [comment]
Is that error in waifu2x.udp.jp? or your hosting server?

**Comment by anonymau5** [comment]
That error is being spit out through the WebUI on my own server.

**Comment by nagadomi** [comment]
Does command line tool work?
```
th waifu2x.lua
```
I don't know what’s happened. Maybe installation environment is broken.

**Comment by anonymau5** [comment]
Sorry for the late response.
I get the following when I enter that command.
```
user@Mami:~/.Waifu2X$ th waifu2x.lua
/usr/local/bin/luajit: /usr/local/share/lua/5.1/nn/Sequential.lua:39: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-9392/cutorch/lib/THC/THCStorage.cu:30
stack traceback:
        [C]: in function 'updateOutput'
        /usr/local/share/lua/5.1/nn/Sequential.lua:39: in function 'forward'
        /home/user/.Waifu2X/lib/reconstruct.lua:41: in function 'reconstruct_rgb'
        /home/user/.Waifu2X/lib/reconstruct.lua:137: in function 'image'
        waifu2x.lua:36: in function 'convert_image'
        waifu2x.lua:116: in function 'waifu2x'
        waifu2x.lua:121: in main chunk
        [C]: in function 'dofile'
        /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x00404270
```

**Comment by nagadomi** [comment]
What is your GPU? It seems failed to allocate video memory.
And, try 
```
th waifu2x.lua -crop_size 32
```

**Comment by anonymau5** [comment]
nVidia GT440 with 1Gb VRAM

The command ends in the same result.

**Comment by nagadomi** [comment]
Maybe this issue is caused by old GPU or torch7(cunn) layer.
The simplest solution is to use a high-end GPU. :cry:

**Comment by anonymau5** [comment]
I was thinking that perhaps that was the issue.
When I can afford it, I'll get a better GPU for my server and see if that alleviates the issue.
As always, thanks for your hard work.

**Comment by anonymau5** [comment]
I have upgraded the card to a 550 TI and receive the following error.
```
user@Mami:~/.Waifu2X$ th waifu2x.lua
/usr/local/bin/luajit: /home/user/.Waifu2X/lib/LeakyReLU.lua:1: attempt to index global 'nn' (a nil value)
stack traceback:
        /home/user/.Waifu2X/lib/LeakyReLU.lua:1: in main chunk
        [C]: in function 'require'
        waifu2x.lua:4: in main chunk
        [C]: in function 'dofile'
        /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x00404270
```

**Comment by anonymau5** [comment]
The issue has been resolved, PCI VGA Palette Snooping was enabled on the BIOS by default.  Disabling it fixes the issue.
