### ISSUE TITLE
Program closes after I start upscaling

### ISSUE THREAD

**Issue by Andrey24SP** [nagadomi/waifu2x#452]
I start the program as usual, put in the videos, select the engine and start it.
After a few seconds, it closes the program and can only be found in task manager, using 0% of everything.
If I try to get back in the program, it won't work, only if I reinstall and restart the pc.
I don't know what do to anymore, tried both beta and stable versions, same problem. 
Any fixes?

**Comment by nagadomi** [comment]
What program are you talking about?
It is probably 3rd party software unrelated to this repository.

**Comment by Andrey24SP** [comment]
> What program are you talking about? It is probably 3rd party software unrelated to this repository.

Yep. My bad, wrong github.
