### ISSUE TITLE
How can I install the waifu2x zip file

### ISSUE THREAD

**Issue by ParsonsPT** [nagadomi/waifu2x#460]
Hello developer I just want to know how can I install the waifu2x zip file.I want to play anime in the best resolution.I am using my phone not pc or computer because I don't have it.

**Comment by nagadomi** [comment]
See https://github.com/nagadomi/nunif/tree/master/windows_package

**Comment by ParsonsPT** [comment]
Will it work for android

**Comment by ParsonsPT** [comment]
> See https://github.com/nagadomi/nunif/tree/master/windows_package

Will it work for android

**Comment by nagadomi** [comment]
Android is not supported.

**Comment by ParsonsPT** [comment]
Thank you I just wanted to know if I could download waifu2x zip file.
