### ISSUE TITLE
Name and what it does is wrong

### ISSUE THREAD

**Issue by Arkz86** [nagadomi/waifu2x#47]
Called 2x and says it does 2x upsampling. But it's not.. It's 4x... It doubles both the horizontal and the vertical. giving you 4 times the original res.

If you feed it a 500x500 image (250,000 pixels)
and set it to 2x
then you will get a 1000x1000 (1,000,000 pixels) image in return.
4 times the resolution of the original image. Should be called waifu4x really

**Comment by edge** [comment]
Highly doubt we're doing this after 4,000 stars.

**Comment by Arkz86** [comment]
Probably not but it's still wrong. The 2x button on http://waifu2x.udp.jp/ should at least say 4x

**Comment by nagadomi** [comment]
That is copied from 2xSAI, scale2x and hq2x.
2x means scaling factor is 2.

**Comment by vitaliylag** [comment]
I agree with Nagadomi. By the way, nobody didn't say that is 2x for all the pixels, it is 2x for one side and 2x for other side. Scale is 2x.

**Comment by Arkz86** [comment]
So making an image 4 times bigger is called scaling 2x because it's the 2x of the vertical and the horizontal? Even though doubling both creates an image 4x bigger? scaling each twice makes it 4x the original scale. four 500x500 images can fit in one 1000x1000 frame.

**Comment by vitaliylag** [comment]
Yes, it's because 2x of the vertical and 2x of the horizontal (or in other words because scale factor is 2x for both of image sides). Yes, it makes image 4x bigger, I think everebody understand it and there's no need to change title, because waifu4x title make people think about 16 times bigger.
