### ISSUE TITLE
Downloadable server image of demo server instance

### ISSUE THREAD

**Issue by Saren-Arterius** [nagadomi/waifu2x#5]
Currently I am using Archlinux and now experience hard time finding dependencies.
It would be very nice to provide demo server's image to download.

**Comment by nagadomi** [comment]
I don't have VM image outside of EC2.
Please use the public AMI.

**Comment by Saren-Arterius** [comment]
Nevermind, I figured out what an AMI is afterwards. 
I failed too much trying to install waifu2x on Archlinux and I am installing this in docker on ubuntu base anyway.

**Comment by Saren-Arterius** [comment]
For people in the future, I have created a docker image: https://registry.hub.docker.com/u/saren/ubuntu-waifu2x/

**Comment by ctrlcctrlv** [comment]
I created an easy Arch Linux PKGBUILD. I appreciate your comments if you get the NVIDIA GPU support working.

https://aur.archlinux.org/packages/waifu2x-git/

Note that this is for tanakamura's build, not nagadomi's.
