### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by Neofranky** [nagadomi/waifu2x#50]
The http://waifu2x.udp.jp/ site is down.

**Comment by nagadomi** [comment]
I fixed this issue yesterday.
waifu2x.udp.jp is hosted on EC2 spot instance (bid-based service). Sometimes the server is down because the server price is very unstable recently.

**Comment by 730730** [comment]
Site is down again.

**Comment by nagadomi** [comment]
Site is down around 3 times a day :neutral_face:

**Comment by Ahrwing** [comment]
It's already fixed, good job!

**Comment by devSera** [comment]
It's down again o/

**Comment by devSera** [comment]
I'm unable to connect to it waifu2x

**Comment by nagadomi** [comment]
waifu2x will revive as long as I live.

**Comment by GamerzHell9137** [comment]
Its been down for 2 days now, what's wrong?

**Comment by fgl-gists** [comment]
> waifu2x will revive as long as I live.

I hope nothing bad has happened to nagadomi :(

**Comment by nagadomi** [comment]
When the price of g2.2xlarge exceeds $1/h, waifu2x.udp.jp will be down.
http://ec2price.com/?product=Linux/UNIX&type=g2.2xlarge&region=us-east-1&window=1

**Comment by nagadomi** [comment]
Currently waifu2x.udp.jp is hosted by the server of pixiv Inc. 
Probably, this issue has fixed.
(There is no restriction on license/development of waifu2x. And I am not a staff of pixiv. pixiv just provides a GPU server for waifu2x.)
