### ISSUE TITLE
Porting to OpenCL

### ISSUE THREAD

**Issue by kode54** [nagadomi/waifu2x#51]
Would it even be possible to use OpenCL to perform the heavy lifting behind this scaler? I don't intend to make it anywhere near real time, I just want to be able to run it without an NVidia card, because I also want to see how well it works at handling large images. Namely, scaling already large (1080p wallpaper) to obscenely large (5120x2880 wallpaper).

I have no idea how much memory that would require, but would a 4GB video card be anywhere near sufficient?

**Comment by kode54** [comment]
Disregard that, my friend just linked me to a C++ port of this scaler, I guess fully software is doable, however slow it may be?

**Comment by leilei-** [comment]
I personally use a GLSL fork of it but that hasn't been updated lately.

https://github.com/ueshita/waifu2x-converter-glsl
