### ISSUE TITLE
Failing to load requirements

### ISSUE THREAD

**Issue by prohulaelk** [nagadomi/waifu2x#52]
After following the installation instructions on Ubuntu 15.04, when I try to run, I get the following error:

    $ th waifu2x.lua
    /usr/local/bin/luajit: /usr/local/share/lua/5.1/trepl/init.lua:363: cuda runtime error (30) : unknown error at /tmp/luarocks_cutorch-scm-1-9445/cutorch/lib/THC/THCGeneral.c:16
    stack traceback:
            [C]: in function 'error'
            /usr/local/share/lua/5.1/trepl/init.lua:363: in function 'require'
            /data/repos/lua/waifu2x/lib/portable.lua:2: in main chunk
            [C]: in function 'require'
            waifu2x.lua:1: in main chunk
            [C]: in function 'dofile'
            /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
            [C]: at 0x00404270

I tried the solution for the similar-looking problem https://github.com/nagadomi/waifu2x/issues/3

    $ echo $LD_LIBRARY_PATH
    /usr/local/lib

But still get the same error

**Comment by nagadomi** [comment]
It's seems to be CUDA installation issue.
Maybe CUDA is not installed correctly.

**Comment by prohulaelk** [comment]
It looks like it is...

    $ nvcc --version                  
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2014 NVIDIA Corporation
    Built on Thu_Jul_17_21:41:27_CDT_2014
    Cuda compilation tools, release 6.5, V6.5.12

I'll try reinstalling using 6.5.14 instead, see if that works.

**Comment by nagadomi** [comment]
try
```
# When CUDA install path=/usr/local/cuda-7.0/
export PATH=/usr/local/cuda-7.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-7.0/lib64:$LD_LIBRARY_PATH
export CUDA_BIN_PATH=/usr/local/cuda-7.0/bin
```

**Comment by prohulaelk** [comment]
Well, you were right about it being a cuda issue - it works if I install cuda 7.5 from the deb package, but not if I build it locally. Thanks!

**Comment by nagadomi** [comment]
That was good.
