### ISSUE TITLE
Failed to load preview images

### ISSUE THREAD

**Issue by expenses** [nagadomi/waifu2x#54]
I installed the dependencies and clones the repository to my home folder and ran the following: 

    th ~/waifu2x/waifu2x.lua 

but recieved the following error:

    /usr/local/bin/luajit: /home/expenses/waifu2x/lib/image_loader.lua:77: images/miku_small.png: failed to load image
    stack traceback:
        [C]: in function 'error'
        /home/expenses/waifu2x/lib/image_loader.lua:77: in function 'load_float'
        /home/expenses/waifu2x/waifu2x.lua:14: in function 'convert_image'
        /home/expenses/waifu2x/waifu2x.lua:116: in function 'waifu2x'
        /home/expenses/waifu2x/waifu2x.lua:121: in main chunk
        [C]: in function 'dofile'
        /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x00405610

Was there a specific location I was meant to clone the repo to? I felt that the read-me was pretty clear up to that point.

**Comment by nagadomi** [comment]
```
cd ~/waifu2x
th waifu2x.lua
```
The working directory must be the source directory.
