### ISSUE TITLE
Error: unknown torch class

### ISSUE THREAD

**Issue by DerKleineGauss** [nagadomi/waifu2x#55]
I installed the dependencies (torch and CUDA) following your installation instructions. Now when I type 'th waifu2x.lua' I get the following error message:

/home/user/torch/install/share/lua/5.1/torch/File.lua:262: unknown Torch class <
V>
stack traceback:
	[C]: in function 'error'
	/home/user/torch/install/share/lua/5.1/torch/File.lua:262: in function 'readObject'
	/home/user/torch/install/share/lua/5.1/torch/File.lua:319: in function 'load'
	waifu2x.lua:32: in function 'convert_image'
	waifu2x.lua:116: in function 'waifu2x'
	waifu2x.lua:121: in main chunk
	[C]: in function 'dofile'
	...user/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:133: in main chunk
	[C]: at 0x00406670

Seems like I am still missing some dependencies.

**Comment by nagadomi** [comment]
I guess the model file is broken.
Could you check the file size and md5sum?
```
% ls -la models/anime_style_art_rgb/*.t7
-rw-rw-r-- 1 nagadomi nagadomi 8596071 Sep  7 15:14 models/anime_style_art_rgb/noise1_model.t7
-rw-rw-r-- 1 nagadomi nagadomi 8605917 Sep  7 15:14 models/anime_style_art_rgb/noise2_model.t7
-rw-rw-r-- 1 nagadomi nagadomi 8596827 Sep  7 15:14 models/anime_style_art_rgb/scale2.0x_model.t7

% md5sum models/anime_style_art_rgb/*.t7
ab1b049fcf6777b46c666549213eea2c  models/anime_style_art_rgb/noise1_model.t7
d6cf9952e5953561ca028fca9e8f336e  models/anime_style_art_rgb/noise2_model.t7
bb4666b71ef8888bbdd215c3dbe67160  models/anime_style_art_rgb/scale2.0x_model.t7
```

**Comment by DerKleineGauss** [comment]
% ls -la models/anime_style_art_rgb/*.t7
-rw-r--r-- 1 user user 8597701 Okt 27 20:54 models/anime_style_art_rgb/noise1_model.t7
-rw-r--r-- 1 user user 8607547 Okt 27 20:54 models/anime_style_art_rgb/noise2_model.t7
-rw-r--r-- 1 user user 8598457 Okt 27 20:54 models/anime_style_art_rgb/scale2.0x_model.t7
% md5sum models/anime_style_art_rgb/*.t7
321eb69525b79d44f797630bb2ff393d  models/anime_style_art_rgb/noise1_model.t7
465a539a2a9839f3c8663a622fdc2cd3  models/anime_style_art_rgb/noise2_model.t7
f5e45f288d6938d4c7eff4e7aaff0421  models/anime_style_art_rgb/scale2.0x_model.t7

**Comment by nagadomi** [comment]
Maybe downloads are incomplete. (or newline char issue?)
Try 
```
git checkout master
git fetch origin
git checkout .
git pull
```
And
```
th waifu2x.lua
```

**Comment by DerKleineGauss** [comment]
I could fix it. Somehow - and I don't know how - several files in the repo were modified (I list below). git reset --hard   helped.

	modified:   .gitignore
	modified:   LICENSE
	modified:   NOTICE
	modified:   README.md
	modified:   appendix/purge_cache.lua
	modified:   appendix/purge_cache.sh
	modified:   appendix/run-web.sh
	modified:   appendix/waifu2x.nginx.conf
	modified:   appendix/waifu2x.upstart.conf
	modified:   assets/index.html
	modified:   assets/index.ja.html
	modified:   assets/index.ru.html
	modified:   cleanup_model.lua
	modified:   convert_data.lua
	modified:   cudnn2cunn.lua
	modified:   export_model.lua
	modified:   images/gen.sh
	modified:   lib/LeakyReLU.lua
	modified:   lib/image_loader.lua
	modified:   lib/iproc.lua
	modified:   lib/minibatch_adam.lua
	modified:   lib/pairwise_transform.lua
	modified:   lib/portable.lua
	modified:   lib/reconstruct.lua
	modified:   lib/settings.lua
	modified:   lib/srcnn.lua
	modified:   models/anime_style_art/noise1_model.t7
	modified:   models/anime_style_art/noise2_model.t7
	modified:   models/anime_style_art/scale2.0x_model.t7
	modified:   models/anime_style_art_rgb/noise1_model.t7
	modified:   models/anime_style_art_rgb/noise2_model.t7
	modified:   models/anime_style_art_rgb/scale2.0x_model.t7
	modified:   models/ukbench/scale2.0x_model.t7
	modified:   train.lua
	modified:   train.sh
	modified:   waifu2x.lua
	modified:   web.lua

**Comment by nagadomi** [comment]
That was good.
I'm not really an expert on git. I am guessing that issue is caused by your git global settings for line ending.
Thanks.
