### ISSUE TITLE
Waifu2x'd images have 16 bit per channel

### ISSUE THREAD

**Issue by expenses** [nagadomi/waifu2x#56]
This is probably intentional, but the images output by waifu2x have 16 bits per channel, which adds considerable size. Is there an an option to lower the output bit-depth?

**Comment by nagadomi** [comment]
The output bit-depth depends on the GraphicsMagick settings.
Probably your GraphicsMagick was compiled with `--with-quantum-depth 16`.
The bit-depth option is currently not supported. I will add it sometime.

**Comment by nagadomi** [comment]
I added -depth option to waifu2x.lua.
And web.lua generates 8 bit-depth PNG by default.
