### ISSUE TITLE
Is it or will it be possible to upscale to custom resolution?

### ISSUE THREAD

**Issue by BrokenSilence** [nagadomi/waifu2x#6]
Is it possible to upscale by a custom amount?
Instead of only 1.6x or 2x?

Like 2.25x..
or 1.5x, or whatever we need?

**Comment by Saren-Arterius** [comment]
If you need 1.5x, you can first resize your image by (1.5/1.6)x using photoshop, then resize it using waifu1.6x, lol.
I think it's because the algorithm's limitation actually.

**Comment by BrokenSilence** [comment]
Yes, I could do that, but its more work on top.. 

I wanted to know if it is possible, or if its limited to that because of the algorithm..

**Comment by drdaxxy** [comment]
There is only Waifu2x. The 1.6x scale setting on the webinterface just scales down from 2x to 1.6x using a more conventional image filter.

Don't know whether it's practical to scale to different factors by changing a few parameters and using different training images, haven't really looked at the code much.

**Comment by nagadomi** [comment]
The model of waifu2x supports only 2x-scaling.
Implementation of 1.6x scaling is here. 
https://github.com/nagadomi/waifu2x/blob/master/web.lua#L150
```
-- upscaling 2x
x = apply_scale2x(x) 
-- downscaling to custom resolution with generic image scaling algorithm.
x = iproc.scale(x, x16[1], x16[2], "Jinc")
```

**Comment by darklx** [comment]
So if I want to upscale to like 5x , I should training a new model ?

**Comment by darklx** [comment]
@nagadomi

**Comment by nagadomi** [comment]
You can apply 2x consecutively. 2x->4x->8x->5x(downscaling), but it will not get much better results.

**Comment by darklx** [comment]
Thanks !
