### ISSUE TITLE
Site lists 2560*2560 as the upload size limit, still won't allow beyond 1280*1280 when trying to resize

### ISSUE THREAD

**Issue by Two-Tone** [nagadomi/waifu2x#61]
Pretty easy to reproduce: Go to http://waifu2x.udp.jp/ and try upscaling any image larger than 1280\*1280 (eg http://i.imgur.com/6aw75KB.png 1280*1281).

**Comment by nagadomi** [comment]
It is the maximum number of pixels of the output image.

2560\*2560=6553600 px
In upscaling:
(1280\*1280)\*4=6553600: ok
(1280\*1281)\*4=6558720: error
(2560\*640)\*4=6553600: ok

Sorry for the confusing UI.

**Comment by Two-Tone** [comment]
You should consider changing it then as it'll gladly do noise reduction on that image.  The old text of "Noise Reduction: 2560x2560px, Upscaling: 1280x1280px" made sense.

**Comment by nagadomi** [comment]
I fixed it in english page.

**Comment by Two-Tone** [comment]
Thanks!
