### ISSUE TITLE
[Suggestion]Donate Button for Extra Features

### ISSUE THREAD

**Issue by fishsurfer** [nagadomi/waifu2x#65]
Upscaling images that are already large may seem to be a bit wasteful, but I'm sure some people (me) have always wanted to do it with some images... but that, of course, is restricted due to it probably being very resource-intensive.

So I suggest a donate button that then removes some of the restrictions (to an extent) that will allow donors to upscale larger images.

**Comment by nagadomi** [comment]
You can use desktop version of waifu2x. It is no limit.
See [VideoHelp Forum](http://forum.videohelp.com/threads/372157-New-upscaling-algorithm-waifu2x) .

I recomment [waifu2x-caffe](https://github.com/lltcggie/waifu2x-caffe) or [tanakamura's waifu2x-converter-cpp](https://github.com/tanakamura/waifu2x-converter-cpp).

**Comment by fishsurfer** [comment]
> You can use desktop version of waifu2x

I tried building it a while back, but it's very bulky (GB's of data) and confusing (setting up CUDA and torch) to set up, so I gave up.
That's why I would suggest an alternative...

**Comment by nagadomi** [comment]
I have no plan to provide a pay service.

waifu2x-caffe and tanakamura's waifu2x-converter-cpp are windows application. There is not need to install Torch and CUDA.
