### ISSUE TITLE
Would this work with some training

### ISSUE THREAD

**Issue by bmaltais** [nagadomi/waifu2x#69]
1st, thank you for your great work. This is awesome.

I have a question. I am making some interesting #devart using Google neural experiment (https://pbs.twimg.com/media/CVHNNKvUYAAVCxA.jpg). My issue is that I can only produce small images of 512px-600px due to GFX memory limits. The usual process to create the art image is that I use a group of source images and apply them as style to a destination image. So the number of sources is very small (like 4 to 6) but usually of good quality and resolution (at least 2 - 3 times the resolution of the resulting image).

I wanted to use those to train a model that could be used to scale the small image. My thinking is that since the small picture is made of elements found in the larger resolution sources they should scale quite well from a model learned from them... Even if there is only a few sources. Am I right?

I tried to create a new learning model but I keep getting no resulting models when following the instructions on the site. I use an Amazon EC2 GPU vm... could this be the issue?

Let me know what you thing. While it is running:

```
th train.lua -method scale -model_dir models/my_model -test ../neural-style/out/beachhousev2.png -style photo
```

I get:

```
{
  random_overlay_rate : 0
  images : "./data/images.t7"
  active_cropping_rate : 0.5
  batch_size : 32
  model_file : "models/my_model/scale2.0x_model.t7"
  scale : 2
  learning_rate : 0.001
  nr_rate : 0.75
  random_unsharp_mask_rate : 0
  max_size : 256
  validation_crops : 80
  thread : -1
  patches : 16
  method : "scale"
  noise_level : 1
  style : "photo"
  gpu : -1
  data_dir : "./data"
  test : "../neural-style/out/beachhousev2.png"
  random_half_rate : 0
  validation_rate : 0.05
  jpeg_chroma_subsampling_rate : 0
  image_list : "./data/image_list.txt"
  model_dir : "models/my_model"
  active_cropping_tries : 10
  crop_size : 46
  inner_epoch : 4
  color : "rgb"
  random_color_noise_rate : 0
  backend : "cunn"
  seed : 11
  epoch : 30
}
# make validation-set
load .. 6
# 1
## resampling
 [==================================== 6/6 ======================================>] ETA: 0ms | Step: 62ms
## update
 [==================================== 96/96 ====================================>] ETA: 0ms | Step: 7ms
{
  loss : 0.029155457838594
}
.
.
.
# validation
current: nan, best: 100000
# 29
## resampling
 [==================================== 6/6 ======================================>] ETA: 0ms | Step: 63ms
## update
 [==================================== 96/96 ====================================>] ETA: 0ms | Step: 7ms
{
  loss : 0.001971720239251
}
# validation
current: nan, best: 100000
## update
 [==================================== 96/96 ====================================>] ETA: 0ms | Step: 7ms
{
  loss : 0.0019699730134259
}
# validation
current: nan, best: 100000
## update
 [==================================== 96/96 ====================================>] ETA: 0ms | Step: 7ms
{
  loss : 0.0019685453993993
}
# validation
current: nan, best: 100000
## update
 [==================================== 96/96 ====================================>] ETA: 0ms | Step: 7ms
{
  loss : 0.0019674577827876
}
# validation
current: nan, best: 100000
# 30
## resampling
 [==================================== 6/6 ======================================>] ETA: 0ms | Step: 58ms
## update
 [==================================== 96/96 ====================================>] ETA: 0ms | Step: 7ms
{
  loss : 0.0019724147989311
}
# validation
current: nan, best: 100000
## update
 [==================================== 96/96 ====================================>] ETA: 0ms | Step: 7ms
{
  loss : 0.0019706121464777
}
# validation
current: nan, best: 100000
## update
 [==================================== 96/96 ====================================>] ETA: 0ms | Step: 7ms
{
  loss : 0.0019693580947609
}
# validation
current: nan, best: 100000
## update
 [==================================== 96/96 ====================================>] ETA: 0ms | Step: 7ms
{
  loss : 0.0019682200185748
}
# validation
current: nan, best: 100000
ubuntu@ip-10-144-123-177:~/waifu2x-photo$ ls
```

The validation always look like:

```
# validation
current: nan, best: 100000
```

This look strange somehow. Is this what it should look like?

**Comment by nagadomi** [comment]
Use `--validation_rate 0.17` option.
`number of validation images = validation_rate * number_training_images`.
`validation_rate` is `0.05` by default. `(int(0.05 * 6) = 0, no validation image)`

I think training on 6 images is unreasonable.
If you want to use photo model, you can use `models/ukbench` or `models/photo`.
```
th waifu2x.lua -model_dir models/ukbench -m scale -i input_image.png -o output.png
```
when you use `photo` branch,
```
th waifu2x.lua -model_dir models/photo -m scale -i input_image.png -o output.png
```
`models/ukbench` was trained on the ukbench dataset (It contains 10000 small photo).  `models/photo` was  trained on 5000 high-resolution raw photograph. Denoising is not supported (work in progress).

**Comment by bmaltais** [comment]
Cool, thank you!

**Comment by bmaltais** [comment]
I did a test run from 19 source pictures I use on and off as texture using a scale of 4 and I am amazed at how good the scaling work. I think running it on a small set work well as long as the same source of info was used to create the original that need scaling.

Can I keep adding pictures to the model or is it that once you are done making it you have to start from scratch? For example, if I add a new picture to my set, do I need to run learning against the 20 images or can I only run it against the 1 new to add the data to the model?

**Comment by nagadomi** [comment]
I think self-similarity based approach(e.g. [SelfExSR](https://github.com/jbhuang0604/SelfExSR)) is better for your use case.
And single image super-resolution has its limit.

**Comment by bmaltais** [comment]
Interesting. I will have to get a matlab trial to give it a try. Too bad there is no free matlab starter version for testing purpose. I don't feel like buying the software just to play around and figure out if it work.

**Comment by bmaltais** [comment]
Also, how should I set the following values since I use hi-res input images:

-max_size
-crop_size

**Comment by nagadomi** [comment]
If your dataset is very small (less than 100), I recommend following option,
```
-random_half_rate 0.5 -random_color_noise_rate 0.5 -patches 1024 -epoch 200
```
But maybe it  will overfit.
