### ISSUE TITLE
Model Questions

### ISSUE THREAD

**Issue by invisiblearts** [nagadomi/waifu2x#72]
As is in `srcnn.lua`, waifu2x uses a 7 layer CNN with no pooling layer. Yet it is suggested in the original paper that the 3-layer one even works better than a deeper net and has better runtime performance.
Since the training set used here to generate the parameters only consists of 7000 images, maybe a simpler net is better?

**Comment by nagadomi** [comment]
In my experiment, deeper net + adam optimizer is slightly better. And, it is related that current scaling model shared the network architecture with denoising model in waifu2x and other optimized implementation of waifu2x. In denoising, deeper net is significantly better than shallow net.
In the cost versus actual performance, shallow scaling model is better, if you want to use scaling model for video encoding, I think.
