### ISSUE TITLE
What hardware re you running on the site? http://waifu2x.udp.jp/

### ISSUE THREAD

**Issue by AUTOMATICxx** [nagadomi/waifu2x#73]
I'm writing a clone of Waitfu2x using OpenCL, which would allow us poor windows users to enjoy our waifus without having to use the web site (and without resolution restrictions).

After a long and unfair fight, I got my GTX970 to scale a 667x1000 image to 1334x2000 in about 40 seconds, which is a great improvement over waifu2x-converter-cpp that does th same thing in about 3 minutes.

But your web site does it in about four seconds.

Does that mean there is a large room for improvement for me, or do you run a large cluster of videocards on your site?

**Comment by nagadomi** [comment]
waifu2x.udp.jp is hosted on EC2 g2.8xlarge instance. g2.8xlarge has four `GRID K520`. The one of API thread uses a single GPU. There are four API thread on server.
And, [waifu2x-converter-cpp modified by tanakamura](https://github.com/tanakamura/waifu2x-converter-cpp) has already supported OpenCL/FMA/AVX/CUDA.
