### ISSUE TITLE
training model on CPU

### ISSUE THREAD

**Issue by djdjoko** [nagadomi/waifu2x#75]
From previous posts I can see that training is quite resource hungry. Would training on CPU machine work?

**Comment by nagadomi** [comment]
Training on CPU is very slow. Probably, it takes few months.
I never provide CPU mode.

**Comment by djdjoko** [comment]
You mentioned that you used up to 32GB RAM that is required for training. Is that VRAM you were talking about?

**Comment by nagadomi** [comment]
I am using GTX760(4GB VRAM) for training. It is good enough.

**Comment by FluffyDiscord** [comment]
how long does it takes to train a model on your gpu?
how many pictures have you used

**Comment by nagadomi** [comment]
6000 images, about 16 hours, on GTX1080.
