### ISSUE TITLE
Cannot launch waifu2x | But I don't know if Torch7 or waifu2x issue... help please.

### ISSUE THREAD

**Issue by GhettoGirl** [nagadomi/waifu2x#77]
Hi nagadomi,
before I begin I want you to know that I really like your image upscaler - it's a fantastic piece of open source software :) 
but after a lot of trial'n'error to get it running offline on my machine (of course with nvidia gpu), I decided to open a issue here.

A little bit of background:
I had a lot of problems getting cuda by itself to work - its now fixed and I can finally run a demo app from the sdk - after even more month of trying to setup stuff I gave up in hope you can guide me a litte. I don't get what could be wrong...

Here is what I did and what is working:
I followed the instructions carefully minor times.
I have a working torch install - played around a bit in interactive mode of it.
I have (after month of frustration) a working cuda setup. (finally)
I have the latest (as of 5th January 2016) waifu2x git version.

I fought against a lot of issues, but this one I cannot fix by myself because I don't understand the lua scripting language:

    /opt/torch/install/bin/luajit: /opt/torch/install/share/lua/5.1/trepl/init.lua:383: /opt/torch/install/share/lua/5.1/trepl/init.lua:383: /opt/torch/install/share/lua/5.1/torch/init.lua:102: bad argument #2 (invalid parent class name nn.Module)
    stack traceback:
            [C]: in function 'error'
            /opt/torch/install/share/lua/5.1/trepl/init.lua:383: in function 'require'
            web.lua:7: in main chunk
            [C]: in function 'dofile'
            /opt/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
            [C]: at 0x00405ea0

What i understaned is that there is a bad argument to function torch.newmetatable()
My guess is that this is a torch issue, rather than a waifu2x issue, but as said I'm out of ideas.

Do you have an idea how to fix this?

Greetings

EDIT: forgot to mention

Linux Ubuntu 15.04 with Kernel 4.3.0
NVIDIA GeForce GTX 980M (Bumblebee setup - NVIDIA optimus)
NVIDIA 358 Driver
CUDA stuff comes from the repos, the one from nvidia.com is NOT working for me.

    optirun th waifu2x.lua -h    <---- triggers error
    th waifu2x.lua -h   <---- triggers the same error
    (optirun) th web.lua  <---- also triggers the same error

**Comment by nagadomi** [comment]
What happens when you run the following command?
```
th -e "require 'nn'"
th -e "require 'cunn'"
```
Try to update modules If you got an error.
```
luarocks install torch
luarocks install cutorch
luarocks install nn
luarocks install cunn
```
(use `sudo` if you needed.)

**Comment by GhettoGirl** [comment]
Thanks for the reply

    # > optirun th -e "require 'cunn'"
    /opt/torch/install/share/lua/5.1/trepl/init.lua:383: /opt/torch/install/share/lua/5.1/trepl/init.lua:383: cuda runtime error (30) : unknown error at /opt/torch/extra/cutorch/lib/THC/THCGeneral.c:16
    $?=0

    # > optirun th -e "require 'nn'"
    $?=0

after updating all 4 modules I get still the same error

I should also mention that 'primusrun' doesn't work when using CUDA (error 38), only 'optirun' works

and just to be sure
    LD_LIBRARY_PATH="/usr/lib/nvidia-current:$LD_LIBRARY_PATH"

**Comment by nagadomi** [comment]
Does this command work?
```
primusrun optirun th waifu2x.lua
```
It seems the issue is caused by CUDA or Hardware environment.
Sorry, I am not knowledgeable about  NVIDIA Optimus.

**Comment by GhettoGirl** [comment]
No this won't work either, I need to try this in a Kernel Virtual Machine with GPU passthrough to get rid of NVIDIA optimus.
My guess is a weird bumblebee bug or a hardware limitation because of having 2 GPUs.

**Comment by GhettoGirl** [comment]
Sorry for not replying for such a long time,
I couldn't run waifu2x in a virtual machine either and I don't have another nvidia machine :(

But I found this one → https://github.com/WL-Amigo/waifu2x-converter-cpp
is this version any good?? at least the produced images are very similar to the online version

except it's slow as hell, I'm very happy with the upscales

greets :)

PS: I think you can close this issue now.

**Comment by nagadomi** [comment]
I recommend following softwares.
- [waifu2x-caffe](https://github.com/lltcggie/waifu2x-caffe) (It is fully compatible with my implementation)
- [tanakamura's waifu2x-converter-cpp](https://github.com/tanakamura/waifu2x-converter-cpp) (It is almost compatible with my implentation. And it needs model file updating. [models/](https://github.com/nagadomi/waifu2x/tree/master/models/anime_style_art_rgb) )

**Comment by YukiSakuma** [comment]
What do you mean waifu2x caffe is fully compatible with your implementation? Can I update the models of waifu2x caffe using your models and how?

**Comment by nagadomi** [comment]
waifu2x-caffe contains latest pretrained model file(json) that is copied from waifu2x(this repo). 
waifu2x: https://github.com/nagadomi/waifu2x/tree/master/models
waifu2x-caffe: https://github.com/lltcggie/waifu2x-caffe/tree/master/bin/models
