### ISSUE TITLE
Should I really use CUDA library to run this code?

### ISSUE THREAD

**Issue by ChrisyehGone** [nagadomi/waifu2x#81]
My Mac has Intel Iris Graphics Hardware. Can I run this code?

**Comment by Luminess** [comment]
Waifu2x uses [nvidia's cuDNN library](https://developer.nvidia.com/cudnn) for hardware accelerated deep learning. Therefore an nvidia GPU with CUDA support is mandatory for running this implementation of waifu2x. However, there is [a reimplementation of the conversion function of waifu2x in C++](https://github.com/tanakamura/waifu2x-converter-cpp) using [the OpenCV library](http://opencv.org/) for hardware accelerated deep learning which does indeed support acceleration using the SSE instruction set your CPU has. Unfortunately, your computer of choice lacks the necessary processing power for any non-laymen level computing task and will result in a degraded performance of waifu2x. Note that the mentioned alternative does not support training models; only the usage of existing ones.

**Comment by nagadomi** [comment]
No. This code requires CUDA and NVIDIA GPU.
