### ISSUE TITLE
An error occured when running your code~!

### ISSUE THREAD

**Issue by ChrisyehGone** [nagadomi/waifu2x#82]
after I ran this cmd -- "th waifu2x.lua ", then it showed that:
/home/chrisyeh/torch/install/bin/luajit: /home/chrisyeh/torch/install/share/lua/5.1/trepl/init.lua:383: /home/chrisyeh/torch/install/share/lua/5.1/trepl/init.lua:383: /home/chrisyeh/torch/install/share/lua/5.1/torch/init.lua:102: bad argument #2 (invalid parent class name nn.Module)
stack traceback:
	[C]: in function 'error'
	/home/chrisyeh/torch/install/share/lua/5.1/trepl/init.lua:383: in function 'require'
	waifu2x.lua:5: in main chunk
	[C]: in function 'dofile'
	...syeh/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
what's going on? Thx for your reply on previous issue.
by the way, Could you please tell which version of lua do you use?

**Comment by nagadomi** [comment]
Did you install CUDA backend?
I replied to #81.

**Comment by ChrisyehGone** [comment]
yes I had intalled it

**Comment by ChrisyehGone** [comment]
Now, I use ubuntu 14.04

**Comment by ChrisyehGone** [comment]
I had change a computer with nvidia geforce 210 and installed cuda by then

**Comment by ChrisyehGone** [comment]
but the error occurs all the time...

**Comment by nagadomi** [comment]
What happens when you run the following command?
```
th -e "require 'nn'"
th -e "require 'cunn'"
```

**Comment by nagadomi** [comment]
Maybe torch7's CUDA module doesn't support GeForce 210 (Compute Capability 1.2).

**Comment by ChrisyehGone** [comment]
chrisyeh@chrisyeh-Lenovo:~/下载/waifu2x$ th -e "require 'cunn'"
.../chrisyeh/torch/install/share/lua/5.1/trepl/init.lua:383: module 'cunn' not found:No LuaRocks module found for cunn
	no field package.preload['cunn']
	no file '/home/chrisyeh/.luarocks/share/lua/5.1/cunn.lua'
	no file '/home/chrisyeh/.luarocks/share/lua/5.1/cunn/init.lua'
	no file '/home/chrisyeh/torch/install/share/lua/5.1/cunn.lua'
	no file '/home/chrisyeh/torch/install/share/lua/5.1/cunn/init.lua'
	no file './cunn.lua'
	no file '/home/chrisyeh/torch/install/share/luajit-2.1.0-beta1/cunn.lua'
	no file '/usr/local/share/lua/5.1/cunn.lua'
	no file '/usr/local/share/lua/5.1/cunn/init.lua'
	no file '/home/chrisyeh/.luarocks/lib/lua/5.1/cunn.so'
	no file '/home/chrisyeh/torch/install/lib/lua/5.1/cunn.so'
	no file '/home/chrisyeh/torch/install/lib/cunn.so'
	no file './cunn.so'
	no file '/usr/local/lib/lua/5.1/cunn.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by nagadomi** [comment]
install cunn.
```
luarocks install cutorch
luarocks install cunn
```

**Comment by ChrisyehGone** [comment]
could you please list out the version of all the environment you install?

**Comment by nagadomi** [comment]
LuaJIT 2.1.0-beta1
CUDA 7.5
gcc 4.9.3
Torch7 modules are not managed under version control. (maybe I am using latest version)

If you got an error from `th -e "require 'cunn'"`, the issue is not related to waifu2x.

**Comment by ChrisyehGone** [comment]
Oh my god~! Maybe my PC can't setup CUDA. I would change my work on Windows and C++.
Thank you all the same~! And last question, does the C++ version contains source codes of waifu2x?

**Comment by nagadomi** [comment]
waifu2x compatible software contains [parameter file](https://github.com/nagadomi/waifu2x/tree/master/models/anime_style_art_rgb) (JSON) of our trained neural network model. The code of waifu2x(this repo) is not contained.

And, see https://github.com/nagadomi/waifu2x/issues/77#issuecomment-172020182
