### ISSUE TITLE
2 new approaches to super-resolution tasks.

### ISSUE THREAD

**Issue by Dringite** [nagadomi/waifu2x#83]
There have been 2 papers published on the subject which appear to beat the current SRCNN method by quite a margin:

http://arxiv.org/abs/1511.04491
http://arxiv.org/abs/1511.04587

**Comment by nagadomi** [comment]
Thanks.
I think current waifu2x model(photo) is also able to beat the original SRCNN.
![results](https://cloud.githubusercontent.com/assets/287255/12935526/9afe7204-cfd9-11e5-80f0-128785ddb5e4.png)
NOTICE: The training dataset of waifu2x is differ from other methods.
