### ISSUE TITLE
Use OpenCL/syCL instead of CUDA. 

### ISSUE THREAD

**Issue by LifeIsStrange** [nagadomi/waifu2x#85]
For use on Intel/AMD and ARM cpus/gpus. 
OpenCL is more powerfull than CUDA and syCL easier. Et with this you could do port on the upcoming HSA. 
AMD has developped an easy transpiler for translating existing cuda code to opencl/sycl code. 
https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP
You can create an issue and ask help to the AMD devs.

**Comment by nagadomi** [comment]
An OpenCL implementation of waifu2x is available at [tanakamura/waifu2x-converter-cpp](https://github.com/tanakamura/waifu2x-converter-cpp#modifided-by-tanakamura).
I won't do it.
