### ISSUE TITLE
Provide training data for comparison

### ISSUE THREAD

**Issue by anjishnu** [nagadomi/waifu2x#88]
Please provide the dataset this model was trained on so that we can compare and benchmark.

**Comment by nagadomi** [comment]
`models/ukbench` is trained by [ukbench](http://www.vis.uky.edu/~stewe/ukbench/).
`models/photo` is trained by [kou's photo collection that is provided by フォトスク]( http://photosku.com/photo/category/%E6%92%AE%E5%BD%B1%E8%80%85/kou/) (unrestricted use)
For `models/anime_style_art_rgb`, I won't provide it.

You can train your dataset with waifu2x. See  [README](https://github.com/nagadomi/waifu2x#training-your-own-model) and [train.sh](https://github.com/nagadomi/waifu2x/blob/master/train.sh)

**Comment by gaohaidong** [comment]
Can we download the png files from the website "kou's photo collection that is provided by フォトスク" ?

**Comment by nagadomi** [comment]
You can download high resolution jpeg files from the website. (I wrote and used a crawling script)
Note that those photos contain high-ISO noise. I used those photos after downscaling it.
