### ISSUE TITLE
waifu2x install OK, validation error HELP!

### ISSUE THREAD

**Issue by cuijia1247** [nagadomi/waifu2x#89]
I install the environment as the instruction. However, there are some errors in the validation step.
when I type' th waifu2x.lua' in the waifu2x fold, here is the error information

cuijia1247@cuijia-Ubuntu:~/torch/waifu2x$ th waifu2x.lua
nil	
/home/cuijia1247/torch/install/bin/luajit: /home/cuijia1247/torch/install/share/lua/5.1/trepl/init.lua:384: /home/cuijia1247/torch/install/share/lua/5.1/trepl/init.lua:384: /home/cuijia1247/torch/install/share/lua/5.1/trepl/init.lua:384: ...247/torch/install/share/lua/5.1/graphicsmagick/Image.lua:303: libGraphicsMagickWand.so: cannot open shared object file: No such file or directory
stack traceback:
	[C]: in function 'error'
	/home/cuijia1247/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	waifu2x.lua:6: in main chunk
	[C]: in function 'dofile'
	...1247/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406620

my system is ubuntu 14.04, cuda 7.0
Who can help me to solve this problem, THX.

**Comment by nagadomi** [comment]
libgraphicsmagick is required.
```
sudo apt-get install libgraphicsmagick-dev
```
I updated `README.md`.

**Comment by cuijia1247** [comment]
Thank you @nagadomi ,after installing libgraphicsmagick-dev, the codes can run.

**Comment by nagadomi** [comment]
That's good.
