### ISSUE TITLE
Did everything, but 'th waifu2x.lua' doesn't run

### ISSUE THREAD

**Issue by Maverik7773** [nagadomi/waifu2x#91]
Title.
Here is there error that I get when I run 'th waifu2x.lua':

maverik7773@ubuntu:~/torch$ th waifu2x.lua
/home/maverik7773/torch/install/bin/luajit: cannot open waifu2x.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	...7773/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
maverik7773@ubuntu:~/torch$ 

I don't have a lot of experience with Linux so I'm not entirely sure what to make of this. Any help would be much appreciated.

Update: Restarted my Ubuntu VM and now I cannot log in, so I guess it's broken. Still, help would be nice so I can avoid this when I try again to set this up.

**Comment by nagadomi** [comment]
>ubuntu:~/torch$

I think your working directory is not waiuf2x source directory.
```
$ cd
$ git clone --depth 1 https://github.com/nagadomi/waifu2x.git
$ cd waifu2x
$ th waifu2x.lua
```
And waifu2x is requried CUDA environment. It might be hard to run on VM.
If you are a windows user, [waifu2x-caffe](https://github.com/lltcggie/waifu2x-caffe) or [waifu2x-conver-cpp](https://github.com/tanakamura/waifu2x-converter-cpp) are simple solution.

**Comment by Maverik7773** [comment]
Wow, I feel stupid. Sorry. And thank you. Now I just have to fix the problem with CUDA.
