### ISSUE TITLE
waifu2x breaks on large image resolutions

### ISSUE THREAD

**Issue by djdjoko** [nagadomi/waifu2x#93]
When the output image are very large (> 70MP) waifu2x breaks and the error I get is the following. Does anyone have a clue what could the reason be and if there is a way to avoid it happening?
Thanks

> unnamed = 0
> stack traceback:
>         .../ubuntu/torch/install/share/lua/5.1/turbo/httpserver.lua:278: in function <.../ubuntu/torch/install/share/lua/5.1/turbo/httpserver.lua:255>
>         [C]: in function 'xpcall'
>         /home/ubuntu/torch/install/share/lua/5.1/turbo/iostream.lua:553: in function </home/ubuntu/torch/install/share/lua/5.1/turbo/iostream.lua:544>
>         [C]: in function 'xpcall'
>         /home/ubuntu/torch/install/share/lua/5.1/turbo/ioloop.lua:573: in function </home/ubuntu/torch/install/share/lua/5.1/turbo/ioloop.lua:572>

**Comment by ADAMPOKE111** [comment]
Might be unrelated but when I try to upscale very large images RAM usage is sometimes an issue. And also check the filenames aren't the same.

**Comment by nagadomi** [comment]
Maybe It's out of memory.
I fixed some unnecessarily memory consumption at https://github.com/nagadomi/waifu2x/commit/57e0f52b412bd3011420bfb93845a1815f821cdc.

**Comment by YukiSakuma** [comment]
I sometimes get that error when using w2x caffe, what I do is decrease the block size or split size and run the program and don't use any memory intensive programs while caffe is processing...
